import { PhysicsConstants } from './types';

export const PHYSICS_CONSTANTS: PhysicsConstants = {
  MAX_ENERGY_PER_LAUNCH: 100,
  TOTAL_ENERGY_BUDGET: 500,
  ENERGY_CONSERVATION_TOLERANCE: 0.05,
  MOMENTUM_CONSERVATION_TOLERANCE: 0.05,
  GRAVITY: 0,
  FRICTION: 0,
  ELASTIC_COEFFICIENT: 0.85,
  PARTICLE_RADIUS: 8,
  MAX_TRAIL_LENGTH: 30,
  FRAME_RATE: 60,
};

export const CANVAS_CONFIG = {
  WIDTH: 800,
  HEIGHT: 500,
  GRID_SIZE: 40,
  CANNON_X: 60,
  CANNON_Y: 250,
};

export const SCORE_CONFIG = {
  PERFECT_COLLISION_BONUS: 50,
  ENERGY_EFFICIENCY_BONUS: 0.5,
  MOMENTUM_ERROR_PENALTY: 30,
  ENERGY_OVER_LIMIT_PENALTY_PER_UNIT: 2,
};
