export enum UserRole {
  DATA_ENTRY = 'DATA_ENTRY',
  REVIEWER = 'REVIEWER',
  SUPERVISOR = 'SUPERVISOR',
  READ_ONLY = 'READ_ONLY'
}

export enum ReceiptStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FROZEN = 'FROZEN',
  SETTLED = 'SETTLED',
  ARCHIVED = 'ARCHIVED'
}

export enum DirtyType {
  MISSING_FIELD = 'MISSING_FIELD',
  CROSS_DAY = 'CROSS_DAY',
  NAME_CHANGED = 'NAME_CHANGED',
  AMOUNT_CONFLICT = 'AMOUNT_CONFLICT',
  QUANTITY_CONFLICT = 'QUANTITY_CONFLICT',
  DUPLICATE_SUBMISSION = 'DUPLICATE_SUBMISSION'
}

export enum AttachmentType {
  IMPLANT_BATCH = 'IMPLANT_BATCH',
  APPOINTMENT_RECORD = 'APPOINTMENT_RECORD',
  SUPPLIER_INVOICE = 'SUPPLIER_INVOICE',
  SECONDARY_CONFIRMATION = 'SECONDARY_CONFIRMATION',
  OTHER = 'OTHER'
}

export enum StateAction {
  CREATE_BATCH = 'CREATE_BATCH',
  UPLOAD_ATTACHMENT = 'UPLOAD_ATTACHMENT',
  SUBMIT = 'SUBMIT',
  REVIEW_APPROVE = 'REVIEW_APPROVE',
  REVIEW_REJECT = 'REVIEW_REJECT',
  REVIEW_OVERRULE = 'REVIEW_OVERRULE',
  FREEZE = 'FREEZE',
  UNFREEZE = 'UNFREEZE',
  SETTLE = 'SETTLE',
  CANCEL = 'CANCEL',
  ARCHIVE = 'ARCHIVE',
  RESTORE = 'RESTORE'
}
