// 农田害虫密度预警 - 示例数据
// 所有数据同源，图表、明细、下载共用此数据集

const BATCH_INFO = {
  batchId: "20260611-A01",
  batchName: "豫东麦区二季度害虫监测",
  runTime: "2026-06-11 08:30:00",
  samplingDate: "2026-06-05 至 2026-06-10",
  operator: "李技术员",
  reviewer: "张研究员",
};

const SITES = [
  { id: "S001", name: "周口市太康县清集镇", district: "太康县", town: "清集镇" },
  { id: "S002", name: "周口市淮阳区临蔡镇", district: "淮阳区", town: "临蔡镇" },
  { id: "S003", name: "商丘市民权县北关镇", district: "民权县", town: "北关镇" },
  { id: "S004", name: "商丘市宁陵县柳河镇", district: "宁陵县", town: "柳河镇" },
  { id: "S005", name: "开封市杞县圉镇镇", district: "杞县", town: "圉镇镇" },
  { id: "S006", name: "开封市通许县竖岗镇", district: "通许县", town: "竖岗镇" },
];

const SPECIES = [
  {
    id: "SP001",
    name: "麦长管蚜",
    scientificName: "Sitobion avenae",
    aliases: ["长管蚜", "麦蚜", "小麦蚜虫", "Sitobion graminis"],
    category: "同翅目 蚜科",
    harmLevel: "高危",
    description: "麦长管蚜是小麦主要害虫之一，以成蚜和若蚜刺吸植物汁液，同时传播小麦黄矮病。",
    controlThreshold: 500,
    photos: [
      { id: "P001", label: "成虫背视图", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=microscope%20photo%20of%20aphid%20sitobion%20avenae%20wheat%20aphid%20dorsal%20view%20scientific%20specimen&image_size=square" },
      { id: "P002", label: "若虫侧面图", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=microscope%20photo%20of%20aphid%20nymph%20side%20view%20wheat%20pest%20scientific&image_size=square" },
      { id: "P003", label: "群体危害状", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20aphid%20colony%20on%20wheat%20leaf%20agricultural%20pest%20damage&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-08", type: "采样记录", content: "太康县清集镇麦田采样，编号TK-0608-03", opinion: "初检阳性" },
      { date: "2026-06-09", type: "显微鉴定", content: "镜检确认麦长管蚜成虫3只、若虫12只", opinion: "物种确认" },
      { date: "2026-06-10", type: "测序验证", content: "COI基因测序，序列与GenBank KU234567.1匹配度99.2%", opinion: "分子验证通过" },
      { date: "2026-06-10", type: "密度评估", content: "调查10点，平均密度620只/亩", opinion: "超阈值预警" },
      { date: "2026-06-11", type: "处理建议", content: "建议喷施吡虫啉3000倍液，7天后复查", opinion: "待复核" },
    ],
  },
  {
    id: "SP002",
    name: "麦二叉蚜",
    scientificName: "Schizaphis graminum",
    aliases: ["二叉蚜", "麦二叉蚜", "绿蚜", "Schizaphis graminum Rondani"],
    category: "同翅目 蚜科",
    harmLevel: "中危",
    description: "麦二叉蚜喜在作物苗期为害，被害部形成枯斑，是传播黄矮病的重要媒介。",
    controlThreshold: 300,
    photos: [
      { id: "P004", label: "无翅成蚜", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=greenbug%20schizaphis%20graminum%20apterous%20adult%20aphid%20micrograph&image_size=square" },
      { id: "P005", label: "有翅型", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=winged%20aphid%20greenbug%20alate%20form%20microscope%20photograph&image_size=square" },
      { id: "P006", label: "为害状", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20leaf%20damaged%20by%20aphids%20yellow%20spots%20agriculture&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-07", type: "采样记录", content: "淮阳区临蔡镇麦田采样，编号HY-0607-01", opinion: "初检阳性" },
      { date: "2026-06-08", type: "显微鉴定", content: "镜检确认麦二叉蚜，前翅中脉分叉特征明显", opinion: "物种确认" },
      { date: "2026-06-09", type: "密度评估", content: "平均密度210只/亩，低于防治阈值", opinion: "低危预警" },
    ],
  },
  {
    id: "SP003",
    name: "小麦红蜘蛛",
    scientificName: "Tetranychus cinnabarinus",
    aliases: ["麦蜘蛛", "红叶螨", "朱砂叶螨", "棉红蜘蛛"],
    category: "蜱螨目 叶螨科",
    harmLevel: "中危",
    description: "小麦红蜘蛛以成螨和若螨刺吸小麦叶片汁液，被害叶片出现黄白色斑点，严重时叶片枯黄。",
    controlThreshold: 200,
    photos: [
      { id: "P007", label: "雌成螨背视", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=red%20spider%20mite%20tetranychus%20dorsal%20view%20microscope%20image&image_size=square" },
      { id: "P008", label: "螨卵群", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=spider%20mite%20eggs%20on%20leaf%20surface%20micrograph&image_size=square" },
      { id: "P009", label: "叶片被害状", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20leaf%20with%20spider%20mite%20damage%20yellow%20speckles&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-07", type: "采样记录", content: "民权县北关镇麦田采样，编号MQ-0607-02", opinion: "初检阳性" },
      { date: "2026-06-08", type: "显微鉴定", content: "镜检确认朱砂叶螨，雌成螨深红色，体侧有黑斑", opinion: "物种确认" },
      { date: "2026-06-09", type: "密度评估", content: "每市尺行长平均186头", opinion: "中危预警" },
      { date: "2026-06-10", type: "处理建议", content: "建议喷施阿维菌素，注意叶背喷施", opinion: "待复核" },
    ],
  },
  {
    id: "SP004",
    name: "粘虫",
    scientificName: "Mythimna separata",
    aliases: ["行军虫", "剃枝虫", "五色虫", "夜盗虫", "Leucania separata"],
    category: "鳞翅目 夜蛾科",
    harmLevel: "高危",
    description: "粘虫是一种迁飞性害虫，幼虫食叶，大发生时可将作物叶片全部食光，造成严重减产。",
    controlThreshold: 20,
    photos: [
      { id: "P010", label: "幼虫正面", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=armyworm%20caterpillar%20mythimna%20separata%20larva%20close%20up&image_size=square" },
      { id: "P011", label: "成虫展翅", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=oriental%20armyworm%20moth%20adult%20wings%20spread%20specimen&image_size=square" },
      { id: "P012", label: "危害状", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20field%20damaged%20by%20armyworm%20caterpillars%20agriculture&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-06", type: "性诱监测", content: "杞县圉镇镇性诱剂诱捕到粘虫成虫12头", opinion: "监测发现" },
      { date: "2026-06-08", type: "田间调查", content: "百步幼虫量18头，以3-4龄为主", opinion: "超阈值预警" },
      { date: "2026-06-09", type: "分子鉴定", content: "COI条形码鉴定为Mythimna separata", opinion: "物种确认" },
      { date: "2026-06-10", type: "处理建议", content: "建议紧急防治，喷施氯虫苯甲酰胺", opinion: "高危预警" },
    ],
  },
  {
    id: "SP005",
    name: "麦秆蝇",
    scientificName: "Meromyza saltatrix",
    aliases: ["麦秆黄蝇", "小麦秆蝇", "麦茎蝇"],
    category: "双翅目 黄潜蝇科",
    harmLevel: "低危",
    description: "麦秆蝇以幼虫钻入小麦茎秆为害，造成枯心苗和白穗，是小麦苗期主要害虫之一。",
    controlThreshold: 50,
    photos: [
      { id: "P013", label: "成虫侧面", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20stem%20fly%20meromyza%20saltatrix%20adult%20side%20view%20micrograph&image_size=square" },
      { id: "P014", label: "幼虫形态", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fly%20larva%20maggot%20wheat%20stem%20pest%20microscope%20image&image_size=square" },
      { id: "P015", label: "为害茎秆", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wheat%20stem%20damaged%20by%20stem%20fly%20larva%20agricultural&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-08", type: "采样记录", content: "通许县竖岗镇麦田采样", opinion: "初检阳性" },
      { date: "2026-06-09", type: "鉴定结果", content: "剥查确认麦秆蝇为害，被害株率1.2%", opinion: "低危" },
    ],
  },
  {
    id: "SP006",
    name: "灰飞虱",
    scientificName: "Laodelphax striatellus",
    aliases: ["灰稻虱", "小稻虱", "稻灰飞虱"],
    category: "同翅目 飞虱科",
    harmLevel: "中危",
    description: "灰飞虱不仅直接刺吸为害，更重要的是传播水稻条纹叶枯病、小麦丛矮病等病毒病。",
    controlThreshold: 100,
    photos: [
      { id: "P016", label: "长翅型成虫", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=small%20brown%20planthopper%20laodelphax%20striatellus%20macropterous%20adult&image_size=square" },
      { id: "P017", label: "短翅型雌虫", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=planthopper%20brachypterous%20female%20adult%20pest%20micrograph&image_size=square" },
      { id: "P018", label: "若虫群", url: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=planthopper%20nymphs%20on%20rice%20leaf%20pest%20colony&image_size=square" },
    ],
    traceRecords: [
      { date: "2026-06-07", type: "采样记录", content: "柳河镇麦田虫口调查", opinion: "初检阳性" },
      { date: "2026-06-08", type: "鉴定确认", content: "灰飞虱成若虫均有，以短翅型为主", opinion: "物种确认" },
      { date: "2026-06-09", type: "带毒检测", content: "ELISA检测丛矮病带毒率8.5%", opinion: "需关注" },
    ],
  },
];

const NEGATIVE_CONTROL = {
  id: "NC-001",
  name: "阴性对照（无菌水）",
  expected: "无检出",
  actual: "麦长管蚜DNA检出",
  status: "异常",
  ctValue: 32.5,
  threshold: 35,
  concentration: "0.02 ng/μL",
  operator: "李技术员",
  testTime: "2026-06-10 14:30",
  anomalyType: "交叉污染",
  initialAssessment: "可能为实验过程中交叉污染，建议重新提取阴性对照进行验证",
  reviewHistory: [
    {
      id: "RH-001",
      user: "王实验员",
      time: "2026-06-10 16:20",
      action: "初次标记异常",
      result: "异常",
      comment: "阴性对照出现扩增曲线，Ct值32.5，疑似污染",
    },
  ],
};

const RECORDS = [
  {
    id: "REC-2026-001",
    siteId: "S001",
    siteName: "周口市太康县清集镇",
    speciesId: "SP001",
    speciesName: "麦长管蚜",
    speciesAlias: "长管蚜",
    density: 620,
    unit: "只/亩",
    level: "高危",
    seqResult: "阳性",
    seqId: "SEQ-A01-001",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-08 09:15",
    operator: "李技术员",
    notes: "麦田中部采样，虫口密度较高",
  },
  {
    id: "REC-2026-002",
    siteId: "S001",
    siteName: "周口市太康县清集镇",
    speciesId: "SP002",
    speciesName: "麦二叉蚜",
    speciesAlias: "二叉蚜",
    density: 180,
    unit: "只/亩",
    level: "低危",
    seqResult: "阳性",
    seqId: "SEQ-A01-002",
    negCtrl: "正常",
    reviewStatus: "已通过",
    reviewHistory: [
      {
        id: "RV-001",
        user: "张研究员",
        time: "2026-06-10 10:30",
        result: "通过",
        comment: "密度低于防治阈值，数据可信，无需防治",
        action: "维持原预警",
      },
    ],
    samplingTime: "2026-06-08 09:15",
    operator: "李技术员",
    notes: "与麦长管蚜混合发生",
  },
  {
    id: "REC-2026-003",
    siteId: "S002",
    siteName: "周口市淮阳区临蔡镇",
    speciesId: "SP002",
    speciesName: "麦二叉蚜",
    speciesAlias: "绿蚜",
    density: 210,
    unit: "只/亩",
    level: "低危",
    seqResult: "阳性",
    seqId: "SEQ-A01-003",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-07 14:20",
    operator: "王技术员",
    notes: "田边虫口略高",
  },
  {
    id: "REC-2026-004",
    siteId: "S003",
    siteName: "商丘市民权县北关镇",
    speciesId: "SP003",
    speciesName: "小麦红蜘蛛",
    speciesAlias: "红叶螨",
    density: 285,
    unit: "头/尺行长",
    level: "中危",
    seqResult: "阳性",
    seqId: "SEQ-A01-004",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-07 10:00",
    operator: "李技术员",
    notes: "干旱少雨，红蜘蛛发生较重",
  },
  {
    id: "REC-2026-005",
    siteId: "S004",
    siteName: "商丘市宁陵县柳河镇",
    speciesId: "SP006",
    speciesName: "灰飞虱",
    speciesAlias: "灰稻虱",
    density: 125,
    unit: "只/㎡",
    level: "中危",
    seqResult: "阳性",
    seqId: "SEQ-A01-005",
    negCtrl: "正常",
    reviewStatus: "已通过",
    reviewHistory: [
      {
        id: "RV-002",
        user: "张研究员",
        time: "2026-06-09 15:45",
        result: "通过",
        comment: "带毒率检测结果已复核，需关注病毒病传播风险",
        action: "维持原预警",
      },
    ],
    samplingTime: "2026-06-07 15:30",
    operator: "赵技术员",
    notes: "靠近稻田区域虫口较多",
  },
  {
    id: "REC-2026-006",
    siteId: "S005",
    siteName: "开封市杞县圉镇镇",
    speciesId: "SP004",
    speciesName: "粘虫",
    speciesAlias: "行军虫",
    density: 18,
    unit: "头/百步",
    level: "高危",
    seqResult: "阳性",
    seqId: "SEQ-A01-006",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-08 08:45",
    operator: "李技术员",
    notes: "粘虫幼虫暴发，已接近防治阈值",
  },
  {
    id: "REC-2026-007",
    siteId: "S005",
    siteName: "开封市杞县圉镇镇",
    speciesId: "SP001",
    speciesName: "麦长管蚜",
    speciesAlias: "麦蚜",
    density: 380,
    unit: "只/亩",
    level: "中危",
    seqResult: "阳性",
    seqId: "SEQ-A01-007",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-08 08:45",
    operator: "李技术员",
    notes: "与粘虫混合发生",
  },
  {
    id: "REC-2026-008",
    siteId: "S006",
    siteName: "开封市通许县竖岗镇",
    speciesId: "SP005",
    speciesName: "麦秆蝇",
    speciesAlias: "麦茎蝇",
    density: 12,
    unit: "株/百株",
    level: "低危",
    seqResult: "阳性",
    seqId: "SEQ-A01-008",
    negCtrl: "正常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-08 11:20",
    operator: "王技术员",
    notes: "被害株率较低，为害较轻",
  },
  {
    id: "REC-2026-009",
    siteId: "S003",
    siteName: "商丘市民权县北关镇",
    speciesId: "SP001",
    speciesName: "麦长管蚜",
    speciesAlias: "小麦蚜虫",
    density: 450,
    unit: "只/亩",
    level: "中危",
    seqResult: "阳性",
    seqId: "SEQ-A01-009",
    negCtrl: "异常",
    reviewStatus: "待复核",
    reviewHistory: [],
    samplingTime: "2026-06-07 10:00",
    operator: "李技术员",
    notes: "阴性对照异常，需注意数据可靠性",
  },
  {
    id: "REC-2026-010",
    siteId: "S004",
    siteName: "商丘市宁陵县柳河镇",
    speciesId: "SP003",
    speciesName: "小麦红蜘蛛",
    speciesAlias: "朱砂叶螨",
    density: 156,
    unit: "头/尺行长",
    level: "低危",
    seqResult: "阳性",
    seqId: "SEQ-A01-010",
    negCtrl: "正常",
    reviewStatus: "已驳回",
    reviewHistory: [
      {
        id: "RV-003",
        user: "张研究员",
        time: "2026-06-09 14:20",
        result: "驳回",
        comment: "鉴定存疑，建议复核螨种形态特征，确认是否为麦圆蜘蛛",
        action: "补充采样",
      },
    ],
    samplingTime: "2026-06-07 15:30",
    operator: "赵技术员",
    notes: "叶背为害为主",
  },
];

const DENSITY_TREND = [
  { date: "06-05", 麦长管蚜: 280, 麦二叉蚜: 150, 小麦红蜘蛛: 210, 粘虫: 5, 灰飞虱: 80, 麦秆蝇: 8 },
  { date: "06-06", 麦长管蚜: 320, 麦二叉蚜: 165, 小麦红蜘蛛: 225, 粘虫: 8, 灰飞虱: 95, 麦秆蝇: 10 },
  { date: "06-07", 麦长管蚜: 380, 麦二叉蚜: 190, 小麦红蜘蛛: 260, 粘虫: 12, 灰飞虱: 110, 麦秆蝇: 11 },
  { date: "06-08", 麦长管蚜: 450, 麦二叉蚜: 210, 小麦红蜘蛛: 280, 粘虫: 15, 灰飞虱: 120, 麦秆蝇: 12 },
  { date: "06-09", 麦长管蚜: 520, 麦二叉蚜: 230, 小麦红蜘蛛: 290, 粘虫: 16, 灰飞虱: 125, 麦秆蝇: 12 },
  { date: "06-10", 麦长管蚜: 580, 麦二叉蚜: 245, 小麦红蜘蛛: 285, 粘虫: 17, 灰飞虱: 128, 麦秆蝇: 12 },
  { date: "06-11", 麦长管蚜: 620, 麦二叉蚜: 260, 小麦红蜘蛛: 278, 粘虫: 18, 灰飞虱: 125, 麦秆蝇: 12 },
];

const OPERATION_HISTORY = [
  {
    id: "OH-001",
    user: "张研究员",
    time: "2026-06-10 15:45",
    action: "复核通过",
    target: "REC-2026-005（灰飞虱 - 柳河镇）",
    description: "复核通过，维持原中危预警等级",
  },
  {
    id: "OH-002",
    user: "张研究员",
    time: "2026-06-10 14:20",
    action: "复核驳回",
    target: "REC-2026-010（小麦红蜘蛛 - 柳河镇）",
    description: "鉴定存疑，驳回要求补充采样验证",
  },
  {
    id: "OH-003",
    user: "张研究员",
    time: "2026-06-10 10:30",
    action: "复核通过",
    target: "REC-2026-002（麦二叉蚜 - 清集镇）",
    description: "复核通过，密度低于阈值无需防治",
  },
  {
    id: "OH-004",
    user: "王实验员",
    time: "2026-06-10 16:20",
    action: "标记异常",
    target: "NC-001（阴性对照）",
    description: "阴性对照出现扩增，标记为异常待查",
  },
  {
    id: "OH-005",
    user: "李技术员",
    time: "2026-06-09 18:00",
    action: "数据上传",
    target: "批次 20260611-A01",
    description: "上传本次监测全部10条记录",
  },
];
