import type { PulleyRecord } from '../types'

export const sampleRecords: PulleyRecord[] = [
  {
    id: 'sample-normal',
    name: '正常记录：1动1定滑轮组',
    pulleyCount: 2,
    movingPulleys: 1,
    fixedPulleys: 1,
    objectWeight: 20,
    weightUnit: 'N',
    frictionCoefficient: 0.05,
    ropeLength: 3,
    ropeLengthUnit: 'm',
    source: '课堂实验',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample-boundary',
    name: '边界记录：3动3定滑轮组',
    pulleyCount: 6,
    movingPulleys: 3,
    fixedPulleys: 3,
    objectWeight: 5,
    weightUnit: 'N',
    frictionCoefficient: 0.3,
    ropeLength: 0.5,
    ropeLengthUnit: 'm',
    source: '极限测试',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sample-bad',
    name: '坏数据：单位混用+无效参数',
    pulleyCount: 3,
    movingPulleys: 2,
    fixedPulleys: 1,
    objectWeight: 50,
    weightUnit: 'g',
    frictionCoefficient: -0.1,
    ropeLength: 50,
    ropeLengthUnit: 'cm',
    source: '学生录入（待修正）',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
