export interface ReplayTask {
  id: string;
  name: string;
  importTime: string;
  totalRecords: number;
  exceptionCount: number;
  reviewedCount: number;
  status: 'processing' | 'completed' | 'pending';
  progress: number;
  description?: string;
}

export type ExceptionType = 'index_invalid' | 'permission_missing' | 'schema_changed' | 'data_inconsistent';
export type Severity = 'high' | 'medium' | 'low';
export type RecordStatus = 'pending' | 'reviewing' | 'confirmed';

export interface ExceptionRecord {
  id: string;
  taskId: string;
  eventId: string;
  type: ExceptionType;
  severity: Severity;
  status: RecordStatus;
  tableName: string;
  sourceService: string;
  eventTime: string;
  assignee?: string;
  description: string;
}

export type ServiceType = 'gateway' | 'api' | 'database' | 'cache' | 'mq';
export type CallStatus = 'success' | 'error' | 'timeout';

export interface CallChainNode {
  id: string;
  recordId: string;
  serviceName: string;
  serviceType: ServiceType;
  timestamp: string;
  durationMs: number;
  requestBody?: string;
  responseBody?: string;
  status: CallStatus;
  order: number;
}

export interface PermissionSnapshot {
  id: string;
  recordId?: string;
  version: string;
  snapshotTime: string;
  isBaseline: boolean;
  description?: string;
  matrix: PermissionMatrixItem[];
  diffFromBaseline?: PermissionDiff[];
}

export interface PermissionMatrixItem {
  id: string;
  role: string;
  user?: string;
  resource: string;
  operations: string[];
  granted: boolean;
}

export type ChangeType = 'add' | 'remove' | 'modify';

export interface PermissionDiff {
  itemId: string;
  field: 'role' | 'resource' | 'operations' | 'granted' | 'user';
  oldValue: any;
  newValue: any;
  changeType: ChangeType;
}

export interface TableSchemaSnapshot {
  id: string;
  recordId?: string;
  tableName: string;
  snapshotTime: string;
  fields: TableField[];
  indexes: TableIndex[];
  ddlStatement: string;
  previousDdl?: string;
}

export interface TableField {
  name: string;
  dataType: string;
  nullable: boolean;
  primaryKey: boolean;
  defaultValue?: string;
  comment?: string;
  ordinalPosition: number;
}

export type IndexType = 'PRIMARY' | 'UNIQUE' | 'NORMAL' | 'FULLTEXT';
export type IndexStatus = 'valid' | 'invalid' | 'missing';

export interface TableIndex {
  name: string;
  fields: string[];
  indexType: IndexType;
  status: IndexStatus;
  invalidReason?: string;
  executionPlanHint?: string;
  cardinality?: number;
}

export interface TreatmentOpinion {
  id: string;
  recordId: string;
  author: string;
  authorRole: string;
  authorAvatar?: string;
  createTime: string;
  content: string;
  autoGenerated: boolean;
  attachments?: Attachment[];
}

export interface Attachment {
  name: string;
  size: number;
  uploadTime: string;
  url?: string;
}

export type ReviewActionType = 'rerun' | 'backfill' | 'manual_confirm';
export type ReviewStatus = 'running' | 'success' | 'failed';
export type LogLevel = 'INFO' | 'WARN' | 'ERROR' | 'SUCCESS';

export interface ReviewActionLog {
  id: string;
  recordId: string;
  actionType: ReviewActionType;
  operator: string;
  startTime: string;
  endTime?: string;
  status: ReviewStatus;
  logLines: LogLine[];
  resultSummary?: string;
}

export interface LogLine {
  timestamp: string;
  level: LogLevel;
  message: string;
}

export interface PermissionAuditVersion {
  id: string;
  version: string;
  publishTime: string;
  operator: string;
  operatorAvatar?: string;
  changeSummary: string;
  affectedTasks: string[];
  affectedRecordCount: number;
  oldSnapshotId: string;
  newSnapshotId: string;
  conclusionBefore: string;
  conclusionAfter: string;
  changeDetails: AuditChangeDetail[];
}

export interface AuditChangeDetail {
  id: string;
  type: ChangeType;
  category: 'permission' | 'role' | 'resource';
  description: string;
  oldValue?: string;
  newValue?: string;
}

export interface FilterState {
  exceptionTypes: ExceptionType[];
  severities: Severity[];
  statuses: RecordStatus[];
  searchKeyword: string;
  dateRange?: { start: string; end: string };
}

export interface AppState {
  tasks: ReplayTask[];
  exceptions: ExceptionRecord[];
  selectedTaskId: string | null;
  filters: FilterState;
}
