import type { Parameter, TimelineEntry, Batch, BatchResultItem } from "@/types";

const now = Date.now();
const day = 86400000;

export const mockParameters: Parameter[] = [
  {
    id: "param-001",
    name: "拓扑路径最大迭代次数",
    unit: "次",
    formula: "k_max = ⌈log₂(n)⌉ + 1",
    formulaExplanation:
      "根据图的节点数 n，取以 2 为底的对数并上取整，再加 1 作为最大迭代次数。当图为空图时，迭代次数为 0。",
    description: "拓扑路径求解算法的最大迭代次数限制，用于防止无限循环。",
    value: 12,
    valueType: "normal",
    status: "approved",
    boundaryConditions: {
      min: 1,
      max: 100,
      mustBeInteger: true,
      mustBePositive: true,
      notes: "通常取 log₂(n) 的 1.5 倍作为安全边界",
    },
    category: "算法参数",
    createdAt: new Date(now - 7 * day).toISOString(),
    updatedAt: new Date(now - 2 * day).toISOString(),
  },
  {
    id: "param-002",
    name: "空图路径集合",
    unit: "条",
    formula: "P(∅) = ∅",
    formulaExplanation:
      "当输入图为空图（顶点集为空）时，路径集合为空集。这不是错误，也不是遗漏，是有明确数学定义的边界情况。",
    description: "空图对应的拓扑路径集合，用于边界条件验证。",
    value: null,
    valueType: "empty_set",
    status: "needs_review",
    boundaryConditions: {
      notes: "空集合 ∅ 与零值不同，表示'没有路径'而不是'路径长度为零'",
    },
    category: "边界参数",
    createdAt: new Date(now - 5 * day).toISOString(),
    updatedAt: new Date(now - 3 * day).toISOString(),
  },
  {
    id: "param-003",
    name: "起点到自身的路径长度",
    unit: "单位长度",
    formula: "d(v, v) = 0",
    formulaExplanation:
      "图论中，任意顶点到自身的最短路径长度为 0。这是距离函数的定义性质之一（非负性、同一性、对称性、三角不等式）。",
    description: "同一顶点到自身的路径长度，用于验证距离公理。",
    value: 0,
    valueType: "zero",
    status: "approved",
    boundaryConditions: {
      min: 0,
      mustBeNonNegative: true,
      notes: "零值是有意义的，不是缺失或错误",
    },
    category: "基础定义",
    createdAt: new Date(now - 10 * day).toISOString(),
    updatedAt: new Date(now - 6 * day).toISOString(),
  },
  {
    id: "param-004",
    name: "邻接矩阵维度",
    unit: "阶",
    formula: "A ∈ ℝ^{n×n}",
    formulaExplanation:
      "邻接矩阵是 n 阶方阵，n 为顶点数。矩阵元素 a_{ij} 表示顶点 i 到顶点 j 是否有边相连。",
    description: "图的邻接矩阵的阶数（行数/列数）。",
    value: 25,
    valueType: "normal",
    status: "pending",
    boundaryConditions: {
      min: 1,
      mustBeInteger: true,
      mustBePositive: true,
    },
    category: "图论基础",
    createdAt: new Date(now - 3 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
  },
  {
    id: "param-005",
    name: "平均路径长度（样本A）",
    unit: "跳数",
    formula: "L = (1/n(n-1)) · Σ_{i≠j} d(v_i, v_j)",
    formulaExplanation:
      "所有顶点对之间最短路径长度的平均值。分母为 n(n-1) 是因为不考虑顶点到自身。样本 A 的统计结果。",
    description: "样本 A 图的平均路径长度统计值。",
    value: 3.72,
    valueType: "normal",
    status: "approved",
    boundaryConditions: {
      min: 0,
      notes: "当图不连通时，部分路径为无穷大，此时只计算连通分量内的平均",
    },
    category: "图统计量",
    createdAt: new Date(now - 4 * day).toISOString(),
    updatedAt: new Date(now - 4 * day).toISOString(),
  },
  {
    id: "param-006",
    name: "平均路径长度（样本B）",
    unit: "跳数",
    formula: "L = (1/n(n-1)) · Σ_{i≠j} d(v_i, v_j)",
    formulaExplanation:
      "所有顶点对之间最短路径长度的平均值。样本 B 的统计结果，与样本 A 为同一参数的两次采样。",
    description: "样本 B 图的平均路径长度统计值，与样本A重复。",
    value: 3.72,
    valueType: "normal",
    status: "duplicate",
    boundaryConditions: {
      min: 0,
    },
    category: "图统计量",
    createdAt: new Date(now - 2 * day).toISOString(),
    updatedAt: new Date(now - 1 * day).toISOString(),
    duplicateOf: "param-005",
  },
  {
    id: "param-007",
    name: "聚类系数阈值",
    unit: "无单位",
    formula: "C ≥ θ_C",
    formulaExplanation:
      "聚类系数判定阈值。当节点的局部聚类系数大于等于此阈值时，认为该节点属于一个紧密连接的社区。",
    description: "用于社区发现的聚类系数阈值参数。",
    value: 0.65,
    valueType: "normal",
    status: "needs_review",
    boundaryConditions: {
      min: 0,
      max: 1,
      notes: "经验取值通常在 0.5 ~ 0.8 之间",
    },
    category: "社区发现",
    createdAt: new Date(now - 6 * day).toISOString(),
    updatedAt: new Date(now - 12 * 3600000).toISOString(),
  },
  {
    id: "param-008",
    name: "孤立点集合",
    unit: "个",
    formula: "S_iso = { v ∈ V | deg(v) = 0 }",
    formulaExplanation:
      "度数为 0 的顶点构成的集合。当图中没有孤立点时，该集合为空集。",
    description: "图中孤立顶点的集合，当前图中无孤立点。",
    value: null,
    valueType: "empty_set",
    status: "pending",
    boundaryConditions: {
      notes: "空集合表示没有孤立点，是正常的边界情况",
    },
    category: "边界参数",
    createdAt: new Date(now - 8 * day).toISOString(),
    updatedAt: new Date(now - 5 * day).toISOString(),
  },
  {
    id: "param-009",
    name: "最小割容量",
    unit: "单位流量",
    formula: "c_min(S, T) = Σ_{e∈(S,T)} c(e)",
    formulaExplanation:
      "将图的顶点划分为 S 和 T 两个集合时，从 S 到 T 的所有边的容量之和的最小值。当图不连通时最小割为 0。",
    description: "s-t 最小割的容量值。",
    value: 0,
    valueType: "zero",
    status: "needs_review",
    boundaryConditions: {
      min: 0,
      mustBeNonNegative: true,
      notes: "零值表示 s 和 t 之间没有通路",
    },
    category: "网络流",
    createdAt: new Date(now - 1 * day).toISOString(),
    updatedAt: new Date(now - 6 * 3600000).toISOString(),
  },
  {
    id: "param-010",
    name: "直径估计误差容忍度",
    unit: "%",
    formula: "|D_est - D_true| / D_true ≤ ε",
    formulaExplanation:
      "直径估计算法的相对误差上限。ε 越小估计越精确，但计算复杂度越高。",
    description: "近似直径计算的误差容忍参数。",
    value: 5.0,
    valueType: "normal",
    status: "approved",
    boundaryConditions: {
      min: 0,
      max: 50,
      notes: "常用取值 1% ~ 10%，折中考量精度与效率",
    },
    category: "近似算法",
    createdAt: new Date(now - 12 * day).toISOString(),
    updatedAt: new Date(now - 9 * day).toISOString(),
  },
  {
    id: "param-011",
    name: "BFS初始队列",
    unit: "个",
    formula: "Q_0 = {s}",
    formulaExplanation:
      "广度优先搜索的初始队列，包含起点 s。当起点不存在时初始队列为空。",
    description: "BFS 算法的初始节点队列。",
    value: 1,
    valueType: "normal",
    status: "approved",
    boundaryConditions: {
      min: 0,
      mustBeInteger: true,
    },
    category: "算法参数",
    createdAt: new Date(now - 15 * day).toISOString(),
    updatedAt: new Date(now - 11 * day).toISOString(),
  },
  {
    id: "param-012",
    name: "负权边集合",
    unit: "条",
    formula: "E_- = { e ∈ E | w(e) < 0 }",
    formulaExplanation:
      "所有边权为负数的边构成的集合。在 Dijkstra 算法中不允许负权边，但 Bellman-Ford 可以处理。",
    description: "图中负权边的集合，当前图不含负权边。",
    value: null,
    valueType: "empty_set",
    status: "approved",
    boundaryConditions: {
      notes: "空集合表示图中没有负权边，Dijkstra 算法适用",
    },
    category: "边界参数",
    createdAt: new Date(now - 11 * day).toISOString(),
    updatedAt: new Date(now - 7 * day).toISOString(),
  },
];

export const mockTimeline: TimelineEntry[] = [
  {
    id: "tl-001",
    parameterId: "param-001",
    parameterName: "拓扑路径最大迭代次数",
    operationType: "create",
    newValue: 10,
    newStatus: "pending",
    reason: "初始录入，根据经验值设定",
    operator: "老叶",
    timestamp: new Date(now - 7 * day).toISOString(),
  },
  {
    id: "tl-002",
    parameterId: "param-001",
    parameterName: "拓扑路径最大迭代次数",
    operationType: "update",
    oldValue: 10,
    newValue: 12,
    oldStatus: "pending",
    newStatus: "needs_review",
    reason: "考虑到大图场景，上调 2 次迭代以确保收敛",
    operator: "老叶",
    timestamp: new Date(now - 4 * day).toISOString(),
  },
  {
    id: "tl-003",
    parameterId: "param-001",
    parameterName: "拓扑路径最大迭代次数",
    operationType: "approve",
    oldValue: 12,
    newValue: 12,
    oldStatus: "needs_review",
    newStatus: "approved",
    reason: "复核通过，12 次迭代在精度和效率之间取得平衡",
    operator: "老叶",
    timestamp: new Date(now - 2 * day).toISOString(),
  },
  {
    id: "tl-004",
    parameterId: "param-002",
    parameterName: "空图路径集合",
    operationType: "create",
    oldValue: undefined,
    newValue: null,
    newStatus: "pending",
    reason: "边界参数补录：空图的路径集合",
    operator: "老叶",
    timestamp: new Date(now - 5 * day).toISOString(),
  },
  {
    id: "tl-005",
    parameterId: "param-002",
    parameterName: "空图路径集合",
    operationType: "rejudge",
    oldStatus: "pending",
    newStatus: "needs_review",
    reason: "空集合容易被误判为缺失，需要标记为特殊状态重点复核",
    operator: "老叶",
    timestamp: new Date(now - 3 * day).toISOString(),
  },
  {
    id: "tl-006",
    parameterId: "param-003",
    parameterName: "起点到自身的路径长度",
    operationType: "create",
    newValue: 0,
    newStatus: "pending",
    reason: "基础定义参数：顶点到自身距离为 0",
    operator: "老叶",
    timestamp: new Date(now - 10 * day).toISOString(),
  },
  {
    id: "tl-007",
    parameterId: "param-003",
    parameterName: "起点到自身的路径长度",
    operationType: "approve",
    oldStatus: "pending",
    newStatus: "approved",
    reason: "零值是图论中的标准定义，非错误",
    operator: "老叶",
    timestamp: new Date(now - 6 * day).toISOString(),
  },
  {
    id: "tl-008",
    parameterId: "param-005",
    parameterName: "平均路径长度（样本A）",
    operationType: "create",
    newValue: 3.72,
    newStatus: "approved",
    reason: "样本 A 统计结果，已验证",
    operator: "老叶",
    timestamp: new Date(now - 4 * day).toISOString(),
  },
  {
    id: "tl-009",
    parameterId: "param-006",
    parameterName: "平均路径长度（样本B）",
    operationType: "create",
    newValue: 3.72,
    newStatus: "duplicate",
    reason: "样本 B 结果与样本 A 一致，疑似重复样本，待确认",
    operator: "老叶",
    timestamp: new Date(now - 1 * day).toISOString(),
    details: { duplicateOf: "param-005" },
  },
  {
    id: "tl-010",
    parameterId: "param-007",
    parameterName: "聚类系数阈值",
    operationType: "supplement",
    oldValue: undefined,
    newValue: 0.65,
    oldStatus: "pending",
    newStatus: "needs_review",
    reason: "补录社区发现模块的阈值参数，基于文献经验值",
    operator: "老叶",
    timestamp: new Date(now - 12 * 3600000).toISOString(),
  },
  {
    id: "tl-011",
    parameterId: "param-009",
    parameterName: "最小割容量",
    operationType: "create",
    newValue: 0,
    newStatus: "needs_review",
    reason: "s-t 最小割为 0，需确认是正常边界情况还是数据异常",
    operator: "老叶",
    timestamp: new Date(now - 6 * 3600000).toISOString(),
  },
];

export const mockBatches: Batch[] = [
  {
    id: "batch-001",
    name: "初始参数录入批次",
    runAt: new Date(now - 10 * day).toISOString(),
    totalCount: 6,
    newCount: 6,
    skippedCount: 0,
    updatedCount: 0,
    errorCount: 0,
  },
  {
    id: "batch-002",
    name: "边界参数补录批次",
    runAt: new Date(now - 5 * day).toISOString(),
    totalCount: 5,
    newCount: 3,
    skippedCount: 2,
    updatedCount: 0,
    errorCount: 0,
    previousBatchId: "batch-001",
  },
  {
    id: "batch-003",
    name: "样本B数据重跑",
    runAt: new Date(now - 1 * day).toISOString(),
    totalCount: 4,
    newCount: 1,
    skippedCount: 2,
    updatedCount: 0,
    errorCount: 1,
    previousBatchId: "batch-002",
  },
];

export const mockBatchResults: BatchResultItem[] = [
  // batch-001
  {
    id: "br-001",
    batchId: "batch-001",
    parameterId: "param-001",
    parameterName: "拓扑路径最大迭代次数",
    resultType: "new",
    reason: "首次录入",
    currentValue: 10,
    currentValueType: "normal",
  },
  {
    id: "br-002",
    batchId: "batch-001",
    parameterId: "param-003",
    parameterName: "起点到自身的路径长度",
    resultType: "new",
    reason: "首次录入",
    currentValue: 0,
    currentValueType: "zero",
  },
  {
    id: "br-003",
    batchId: "batch-001",
    parameterId: "param-004",
    parameterName: "邻接矩阵维度",
    resultType: "new",
    reason: "首次录入",
    currentValue: 25,
    currentValueType: "normal",
  },
  {
    id: "br-004",
    batchId: "batch-001",
    parameterId: "param-005",
    parameterName: "平均路径长度（样本A）",
    resultType: "new",
    reason: "首次录入",
    currentValue: 3.72,
    currentValueType: "normal",
  },
  {
    id: "br-005",
    batchId: "batch-001",
    parameterId: "param-010",
    parameterName: "直径估计误差容忍度",
    resultType: "new",
    reason: "首次录入",
    currentValue: 5.0,
    currentValueType: "normal",
  },
  {
    id: "br-006",
    batchId: "batch-001",
    parameterId: "param-011",
    parameterName: "BFS初始队列",
    resultType: "new",
    reason: "首次录入",
    currentValue: 1,
    currentValueType: "normal",
  },
  // batch-002
  {
    id: "br-007",
    batchId: "batch-002",
    parameterId: "param-002",
    parameterName: "空图路径集合",
    resultType: "new",
    reason: "边界参数新增",
    currentValue: null,
    currentValueType: "empty_set",
  },
  {
    id: "br-008",
    batchId: "batch-002",
    parameterId: "param-008",
    parameterName: "孤立点集合",
    resultType: "new",
    reason: "边界参数新增",
    currentValue: null,
    currentValueType: "empty_set",
  },
  {
    id: "br-009",
    batchId: "batch-002",
    parameterId: "param-012",
    parameterName: "负权边集合",
    resultType: "new",
    reason: "边界参数新增",
    currentValue: null,
    currentValueType: "empty_set",
  },
  {
    id: "br-010",
    batchId: "batch-002",
    parameterId: "param-001",
    parameterName: "拓扑路径最大迭代次数",
    resultType: "skipped",
    reason: "参数已存在且值未变化",
    previousValue: 10,
    currentValue: 10,
    previousValueType: "normal",
    currentValueType: "normal",
  },
  {
    id: "br-011",
    batchId: "batch-002",
    parameterId: "param-003",
    parameterName: "起点到自身的路径长度",
    resultType: "skipped",
    reason: "参数已存在且值未变化",
    previousValue: 0,
    currentValue: 0,
    previousValueType: "zero",
    currentValueType: "zero",
  },
  // batch-003
  {
    id: "br-012",
    batchId: "batch-003",
    parameterId: "param-006",
    parameterName: "平均路径长度（样本B）",
    resultType: "new",
    reason: "新增样本 B，疑似与样本 A 重复",
    currentValue: 3.72,
    currentValueType: "normal",
  },
  {
    id: "br-013",
    batchId: "batch-003",
    parameterId: "param-005",
    parameterName: "平均路径长度（样本A）",
    resultType: "skipped",
    reason: "参数已存在且值完全相同",
    previousValue: 3.72,
    currentValue: 3.72,
    previousValueType: "normal",
    currentValueType: "normal",
  },
  {
    id: "br-014",
    batchId: "batch-003",
    parameterId: "param-007",
    parameterName: "聚类系数阈值",
    resultType: "skipped",
    reason: "参数已存在且值未变化",
    previousValue: 0.65,
    currentValue: 0.65,
    previousValueType: "normal",
    currentValueType: "normal",
  },
  {
    id: "br-015",
    batchId: "batch-003",
    parameterId: "param-invalid-1",
    parameterName: "格式异常参数",
    resultType: "error",
    reason: "参数值格式错误：应为数值但收到字符串",
  },
];
