import type { Question } from '@/types';

export const mockQuestions: Question[] = [
  {
    id: 'Q001',
    name: '一元一次方程入门',
    difficulty: 2,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.15,
    dependencies: [],
    notes: '旧表数据，正确率较高',
    source: 'legacy_sheet',
  },
  {
    id: 'Q002',
    name: '移项变号法则应用',
    difficulty: 3,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.28,
    dependencies: ['Q001'],
    notes: '共享盘错题，常出现符号错误',
    source: 'shared_drive',
  },
  {
    id: 'Q003',
    name: '方程解的检验',
    difficulty: 2,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.12,
    dependencies: ['Q001'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q004',
    name: '含括号一元一次方程',
    difficulty: 3,
    chapter: '第二章-进阶应用',
    unit: '分钟',
    errorRate: 0.35,
    dependencies: ['Q002'],
    notes: '草稿备注：去括号时符号易错',
    source: 'draft_note',
  },
  {
    id: 'Q005',
    name: '去分母解方程',
    difficulty: 4,
    chapter: '第二章-进阶应用',
    unit: '分钟',
    errorRate: 0.48,
    dependencies: ['Q004'],
    notes: '共享盘高频错题，漏乘常数项是重灾区',
    source: 'shared_drive',
  },
  {
    id: 'Q006',
    name: '同解方程判定',
    difficulty: 3,
    chapter: '第二章-进阶应用',
    unit: '分钟',
    errorRate: 0.32,
    dependencies: ['Q003'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q007',
    name: '含参数方程讨论',
    difficulty: 5,
    chapter: '第三章-综合训练',
    unit: null,
    errorRate: 0.62,
    dependencies: ['Q005'],
    notes: '单位从草稿迁移时丢失，原应为"分钟"',
    source: 'draft_note',
  },
  {
    id: 'Q008',
    name: '绝对值方程基础',
    difficulty: 4,
    chapter: '第三章-综合训练',
    unit: '分钟',
    errorRate: 0.55,
    dependencies: ['Q005'],
    notes: '共享盘错题，多解漏解情况多',
    source: 'shared_drive',
  },
  {
    id: 'Q009',
    name: '方程应用题-行程问题',
    difficulty: 4,
    chapter: '第三章-综合训练',
    unit: '分钟',
    errorRate: 0.42,
    dependencies: ['Q004', 'Q006'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q010',
    name: '方程应用题-工程问题',
    difficulty: 4,
    chapter: '第三章-综合训练',
    unit: '分钟',
    errorRate: 0.45,
    dependencies: ['Q009'],
    notes: '草稿备注：需配合Q009讲',
    source: 'draft_note',
  },
  {
    id: 'Q011',
    name: '方程应用题-浓度问题',
    difficulty: 5,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.68,
    dependencies: ['Q010'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q012',
    name: '方程组消元法-代入',
    difficulty: 3,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.30,
    dependencies: ['Q005'],
    notes: '同分对比组1',
    source: 'legacy_sheet',
  },
  {
    id: 'Q013',
    name: '方程组消元法-加减',
    difficulty: 4,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.38,
    dependencies: ['Q012'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q014',
    name: '三元一次方程组',
    difficulty: 5,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.58,
    dependencies: ['Q013'],
    notes: '共享盘数据',
    source: 'shared_drive',
  },
  {
    id: 'Q015',
    name: '方程组应用题-鸡兔同笼',
    difficulty: 3,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.30,
    dependencies: ['Q012'],
    notes: '同分对比组2，与Q012评分相同，观察排序稳定性',
    source: 'draft_note',
  },
  {
    id: 'Q016',
    name: '不定方程整数解',
    difficulty: 5,
    chapter: '第五章-冲刺模拟',
    unit: '分钟',
    errorRate: 0.72,
    dependencies: ['Q014'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q017',
    name: '方程综合选填压轴',
    difficulty: 5,
    chapter: '第五章-冲刺模拟',
    unit: '分钟',
    errorRate: 0.75,
    dependencies: ['Q008', 'Q011', 'Q014'],
    notes: '共享盘，高区分度题',
    source: 'shared_drive',
  },
  {
    id: 'Q018',
    name: '方程综合解答压轴',
    difficulty: 5,
    chapter: '第五章-冲刺模拟',
    unit: '分钟',
    errorRate: 0.82,
    dependencies: ['Q017'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q019',
    name: '简易方程热身',
    difficulty: 1,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.08,
    dependencies: [],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q020',
    name: '等式性质辨析',
    difficulty: 2,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.22,
    dependencies: ['Q019'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q021',
    name: '实际问题列方程',
    difficulty: 3,
    chapter: '第二章-进阶应用',
    unit: '分钟',
    errorRate: 0.36,
    dependencies: ['Q020'],
    notes: '草稿备注：审题是关键',
    source: 'draft_note',
  },
  {
    id: 'Q022',
    name: '方程解的讨论',
    difficulty: 4,
    chapter: '第三章-综合训练',
    unit: '分钟',
    errorRate: 0.50,
    dependencies: ['Q021'],
    notes: '',
    source: 'legacy_sheet',
  },
  {
    id: 'Q023',
    name: '含绝对值综合题',
    difficulty: null,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.60,
    dependencies: ['Q008', 'Q022'],
    notes: '评分缺失，从旧表导入时未带出难度分',
    source: 'legacy_sheet',
  },
  {
    id: 'Q024',
    name: '方程与不等式综合',
    difficulty: 5,
    chapter: '第四章-拓展提升',
    unit: '分钟',
    errorRate: 0.65,
    dependencies: ['Q023'],
    notes: 'Q023下游，受评分缺失级联影响',
    source: 'legacy_sheet',
  },
  {
    id: 'Q025',
    name: '新定义方程问题',
    difficulty: 5,
    chapter: '第五章-冲刺模拟',
    unit: '分钟',
    errorRate: 0.78,
    dependencies: ['Q024'],
    notes: '',
    source: 'shared_drive',
  },
  {
    id: 'Q026',
    name: '方程探究性问题',
    difficulty: 4,
    chapter: '第五章-冲刺模拟',
    unit: '分钟',
    errorRate: 0.63,
    dependencies: ['Q023'],
    notes: 'Q023下游，受评分缺失级联影响',
    source: 'legacy_sheet',
  },
  {
    id: 'Q027',
    name: '循环依赖测试A',
    difficulty: 3,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.25,
    dependencies: ['Q028'],
    notes: '人工构造的循环依赖，用于演示失败原因',
    source: 'manual',
  },
  {
    id: 'Q028',
    name: '循环依赖测试B',
    difficulty: 3,
    chapter: '第一章-基础概念',
    unit: '分钟',
    errorRate: 0.25,
    dependencies: ['Q027'],
    notes: '与Q027互相依赖，应被检测并跳过',
    source: 'manual',
  },
  {
    id: 'Q029',
    name: '引用不存在前置题',
    difficulty: 3,
    chapter: '第二章-进阶应用',
    unit: '分钟',
    errorRate: 0.30,
    dependencies: ['Q999'],
    notes: '引用不存在的Q999，应标记错误但不阻塞',
    source: 'manual',
  },
];
