import { ProductionData } from '@/types';

export const mockProductionData: ProductionData = {
  id: 'line-2026-001',
  name: '青铜文物修复生产线节拍',
  totalDuration: 480,
  generatedAt: '2026-06-07 09:30:00',
  mandarinExplanation: '',
  lanes: [
    {
      id: 'lane-1',
      name: '前期准备',
      order: 0,
      nodes: [
        {
          id: 'node-1-1',
          laneId: 'lane-1',
          title: '文物登记建档',
          startTime: 0,
          duration: 60,
          status: 'normal',
          anomalyType: 'none',
          manualNote: '登记编号 Q-2026-042，出土时表面有轻微土锈',
          colorHex: '#A7F3D0',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: true,
          hitDetectionResult: 'passed',
          nextAction: '无需操作',
        },
        {
          id: 'node-1-2',
          laneId: 'lane-1',
          title: '拍照留底',
          startTime: 60,
          duration: 45,
          status: 'warning',
          anomalyType: 'need_material',
          manualNote: '侧面照片只拍了一张，需要补拍45度角细节，光线可能不够',
          colorHex: '#F59E0B',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: false,
          hitDetectionResult: 'pending',
          nextAction: '补拍侧面细节照片，保证光线充足',
        },
      ],
    },
    {
      id: 'lane-2',
      name: '清洗脱盐',
      order: 1,
      nodes: [
        {
          id: 'node-2-1',
          laneId: 'lane-2',
          title: '机械除尘',
          startTime: 105,
          duration: 30,
          status: 'normal',
          anomalyType: 'none',
          manualNote: '使用软毛刷，力度适中，无划痕',
          colorHex: '#A7F3D0',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: true,
          hitDetectionResult: 'passed',
          nextAction: '无需操作',
        },
        {
          id: 'node-2-2',
          laneId: 'lane-2',
          title: '化学脱盐',
          startTime: 135,
          duration: 120,
          status: 'error',
          anomalyType: 'need_caliber',
          manualNote: '浸泡时间比原定多了6小时，这个得改一下记录里的时间',
          colorHex: '#E11D48',
          colorOutOfBounds: true,
          colorBoundReason: '节点颜色色值 #E11D48 超出文保记录色系允许范围（允许范围 #A7F3D0 至 #F59E0B），品红色调属于禁止使用的警示色系，会误导评审对严重程度的判断，需要改为标准异常色系',
          hasScreenshot: true,
          hitDetectionResult: 'failed',
          nextAction: '修改浸泡时长记录口径，同步更新色值至标准异常范围',
        },
      ],
    },
    {
      id: 'lane-3',
      name: '修复加固',
      order: 2,
      nodes: [
        {
          id: 'node-3-1',
          laneId: 'lane-3',
          title: '病害分析',
          startTime: 255,
          duration: 60,
          status: 'normal',
          anomalyType: 'none',
          manualNote: '表面点状腐蚀共17处，未见深层穿透',
          colorHex: '#A7F3D0',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: true,
          hitDetectionResult: 'passed',
          nextAction: '无需操作',
        },
        {
          id: 'node-3-2',
          laneId: 'lane-3',
          title: '补配缺损',
          startTime: 315,
          duration: 90,
          status: 'warning',
          anomalyType: 'need_material',
          manualNote: '缺失的耳部配了锡青铜，需要附材料检测报告',
          colorHex: '#F59E0B',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: false,
          hitDetectionResult: 'pending',
          nextAction: '补充锡青铜材料检测报告扫描件',
        },
        {
          id: 'node-3-3',
          laneId: 'lane-3',
          title: '缓蚀封护',
          startTime: 405,
          duration: 60,
          status: 'error',
          anomalyType: 'need_caliber',
          manualNote: 'B72浓度写的是15%但实际用了10%，这里需要改回真实值',
          colorHex: '#E11D48',
          colorOutOfBounds: true,
          colorBoundReason: '节点颜色使用品红 #E11D48，根据文保记录规范，除安全事故外禁止使用品红色系，该异常属于口径偏差，应改为标准异常色 #F59E0B，避免评审误判为严重事故',
          hasScreenshot: false,
          hitDetectionResult: 'failed',
          nextAction: '修正B72丙酮溶液浓度记录，同步将节点色值改为标准异常色',
        },
      ],
    },
    {
      id: 'lane-4',
      name: '验收归档',
      order: 3,
      nodes: [
        {
          id: 'node-4-1',
          laneId: 'lane-4',
          title: '质检复核',
          startTime: 465,
          duration: 30,
          status: 'warning',
          anomalyType: 'need_material',
          manualNote: '复核人签字页还没有扫描进来',
          colorHex: '#F59E0B',
          colorOutOfBounds: false,
          colorBoundReason: '',
          hasScreenshot: false,
          hitDetectionResult: 'pending',
          nextAction: '扫描复核人签字页并上传归档',
        },
      ],
    },
  ],
};
