BASE_TOKEN = "BnqgbC7MvaP4DFsQYfhcwUdrn7f"

TABLES = {
    "artist_contract": "tblSmzmcaNhkORGM",
    "exhibition": "tblpoCDvMbITzjbD",
    "inventory": "tblk9xEC5HUPLfHu",
    "sales_order": "tbl0Ctz6jOyMKA2p",
    "return_record": "tbl4ANIvouiwG41n",
    "profit_share": "tblRfjxTBfgZrJRT",
    "exception": "tblHYqghhwpWVfTj",
}

FIELD_NAMES = {
    "artist_contract": {
        "name": "艺术家姓名",
        "contract_no": "合同编号",
        "start_date": "合同生效日期",
        "end_date": "合同到期日期",
        "profit_ratio": "分润比例",
        "status": "合同状态",
        "notes": "备注",
    },
    "exhibition": {
        "name": "展会名称",
        "location": "展会地点",
        "start_date": "开始日期",
        "end_date": "结束日期",
        "status": "展会状态",
    },
    "inventory": {
        "print_no": "版画编号",
        "title": "作品名称",
        "artist": "艺术家",
        "edition": "版数",
        "material": "材质",
        "size": "尺寸",
        "year": "创作年份",
        "inbound_date": "入库日期",
        "status": "库存状态",
        "locked_exhibition": "锁定展会",
        "locked_time": "锁定时间",
        "value": "当前价值",
        "source": "数据来源",
        "has_duplicate": "是否编号重复",
        "notes": "备注",
    },
    "sales_order": {
        "order_no": "订单编号",
        "order_date": "订单日期",
        "exhibition": "所属展会",
        "customer": "客户名称",
        "contact": "联系方式",
        "inventory": "关联版画",
        "print_no": "版画编号",
        "amount": "销售金额",
        "payment_status": "收款状态",
        "order_status": "订单状态",
        "contract_ratio": "合同分润比例",
        "source": "数据来源",
        "notes": "备注",
    },
    "return_record": {
        "return_no": "退货编号",
        "return_date": "退货日期",
        "sales_order": "关联订单",
        "inventory": "关联版画",
        "print_no": "版画编号",
        "original_exhibition": "原销售展会",
        "return_exhibition": "退货展会",
        "is_cross_exhibition": "是否跨展退货",
        "reason": "退货原因",
        "return_amount": "退货金额",
        "refund_status": "退款状态",
        "return_status": "退货状态",
        "notes": "备注",
    },
    "profit_share": {
        "calc_date": "分润计算日期",
        "artist": "艺术家",
        "sales_order": "关联订单",
        "inventory": "关联版画",
        "print_no": "版画编号",
        "sales_amount": "销售金额",
        "contract_ratio": "合同分润比例",
        "actual_ratio": "实际分润比例",
        "ratio_abnormal": "比例是否异常",
        "artist_share": "艺术家分润金额",
        "gallery_share": "画廊分润金额",
        "status": "分润状态",
        "has_return": "是否有退货关联",
        "return_record": "关联退货",
        "trace_id": "追溯ID",
        "notes": "备注",
    },
    "exception": {
        "exception_date": "预警日期",
        "exception_type": "异常类型",
        "exception_level": "异常等级",
        "print_no": "关联版画编号",
        "table_name": "关联表名",
        "record_id": "关联记录ID",
        "description": "异常描述",
        "process_status": "处理状态",
        "process_result": "处理结果",
        "process_date": "处理日期",
        "notes": "备注",
    },
}

STATUS_OPTIONS = {
    "contract": ["生效中", "已过期", "已终止"],
    "exhibition": ["未开始", "进行中", "已结束"],
    "inventory": ["在库", "已锁定", "已售出", "已退货", "异常"],
    "payment": ["未收款", "部分收款", "已收款"],
    "order": ["待确认", "已确认", "已发货", "已完成", "已取消"],
    "return": ["待审核", "已审核", "已入库", "已作废"],
    "refund": ["待退款", "部分退款", "已退款"],
    "profit_share": ["待计算", "待审核", "已确认", "已发放", "已驳回"],
    "exception_type": ["编号重复", "退货跨展", "合同比例错误", "库存状态异常", "数据格式错误"],
    "exception_level": ["高", "中", "低"],
    "process": ["待处理", "处理中", "已处理", "已忽略"],
    "data_source": ["批量导入", "手工录入", "系统生成", "展会现场"],
}
