import type { PocketRecord } from '@/types';

export function generateMockRecords(): PocketRecord[] {
  const now = new Date().toISOString();

  const records: PocketRecord[] = [
    {
      id: 'rec_mock_001',
      originalRowNumber: 2,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'CDK2',
      pocketCoordinates: { x: 12.5, y: -8.3, z: 24.1 },
      affinity: 45.2,
      cameraAngle: { azimuth: 45, elevation: 30, distance: 50 },
      reviewStatus: 'usable',
      imageName: 'cdk2_pocket_001.png',
      sourceNote: '标准实验流程，结果可靠',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_002',
      originalRowNumber: 3,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'CDK6',
      pocketCoordinates: { x: 15.2, y: -3.1, z: 28.7 },
      affinity: 38.9,
      reviewStatus: 'pending',
      anomalyType: 'camera_lost',
      anomalyNote: '相机视角参数缺失，无法恢复三维视图',
      imageName: 'cdk6_pocket_002.png',
      sourceNote: '第3行视角参数丢失，需重新生成',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_003',
      originalRowNumber: 4,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'EGFR',
      pocketCoordinates: { x: 890.5, y: -45.2, z: 120.3 },
      affinity: 52.1,
      cameraAngle: { azimuth: 120, elevation: 15, distance: 45 },
      reviewStatus: 'unusable',
      anomalyType: 'data_conflict',
      anomalyNote: '三维模型坐标与点云切片参数不一致，需人工复核',
      imageName: 'egfr_pocket_003.png',
      sourceNote: '坐标超出正常范围，疑似单位转换错误',
      processingOpinion: '建议重新运行坐标校准脚本',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_004',
      originalRowNumber: 5,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'AKT1',
      pocketCoordinates: { x: -5.8, y: 12.4, z: -18.6 },
      affinity: 62.7,
      cameraAngle: { azimuth: 270, elevation: 45, distance: 60 },
      reviewStatus: 'usable',
      imageName: 'akt1_pocket_004.png',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_005',
      originalRowNumber: 6,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: '',
      pocketCoordinates: { x: 0, y: 0, z: 0 },
      affinity: NaN as unknown as number,
      reviewStatus: 'unusable',
      anomalyType: 'format_error',
      anomalyNote: '必填字段缺失或格式错误，记录可能不完整',
      sourceNote: '原始第6行数据不完整，蛋白名缺失',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_006',
      originalRowNumber: 7,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'MAPK1',
      pocketCoordinates: { x: 22.1, y: 15.6, z: -8.4 },
      affinity: 71.3,
      cameraAngle: { azimuth: 180, elevation: -20, distance: 55 },
      reviewStatus: 'usable',
      imageName: 'mapk1_pocket_006.png',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_007',
      originalRowNumber: 8,
      sourceFile: 'pocket_analysis_batch1.csv',
      proteinName: 'JAK2',
      pocketCoordinates: { x: -18.3, y: 22.7, z: 35.2 },
      affinity: 29.8,
      cameraAngle: { azimuth: 400, elevation: 30, distance: 50 },
      reviewStatus: 'pending',
      anomalyType: 'camera_lost',
      anomalyNote: '相机视角参数超出有效范围，三维模型可能无法正确显示',
      imageName: 'jak2_pocket_007.png',
      sourceNote: '方位角400°超出正常0-360范围',
      processingOpinion: '已联系仿真工程师确认参数有效性',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_008',
      originalRowNumber: 2,
      sourceFile: 'pocket_analysis_batch2.csv',
      proteinName: 'BRAF',
      pocketCoordinates: { x: 33.4, y: -12.8, z: 19.5 },
      affinity: 55.6,
      cameraAngle: { azimuth: 90, elevation: 60, distance: 48 },
      reviewStatus: 'usable',
      imageName: 'braf_pocket_008.png',
      sourceNote: '第二批数据，质控已通过',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_009',
      originalRowNumber: 3,
      sourceFile: 'pocket_analysis_batch2.csv',
      proteinName: 'PIK3CA',
      pocketCoordinates: { x: 7.2, y: 28.9, z: -22.1 },
      affinity: 41.4,
      cameraAngle: { azimuth: 225, elevation: 25, distance: 52 },
      reviewStatus: 'pending',
      imageName: 'pik3ca_pocket_009.png',
      sourceNote: '亲和力略低于阈值，待仿真工程师复核',
      reviewNote: '数值偏低但格式正常，建议复核',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rec_mock_010',
      originalRowNumber: 4,
      sourceFile: 'pocket_analysis_batch2.csv',
      proteinName: 'KRAS',
      pocketCoordinates: { x: -11.5, y: -6.7, z: 14.8 },
      affinity: 68.2,
      cameraAngle: { azimuth: 315, elevation: 40, distance: 47 },
      reviewStatus: 'usable',
      imageName: 'kras_pocket_010.png',
      createdAt: now,
      updatedAt: now,
    },
  ];

  return records;
}

export const SAMPLE_CSV = `row,protein,x,y,z,affinity,azimuth,elevation,distance,image,note
2,CDK2,12.5,-8.3,24.1,45.2,45,30,50,cdk2_pocket_001.png,标准实验流程，结果可靠
3,CDK6,15.2,-3.1,28.7,38.9,,,,cdk6_pocket_002.png,第3行视角参数丢失，需重新生成
4,EGFR,890.5,-45.2,120.3,52.1,120,15,45,egfr_pocket_003.png,坐标超出正常范围，疑似单位转换错误
5,AKT1,-5.8,12.4,-18.6,62.7,270,45,60,akt1_pocket_004.png,
6,,0,0,0,,,,,原始第6行数据不完整
7,MAPK1,22.1,15.6,-8.4,71.3,180,-20,55,mapk1_pocket_006.png,
8,JAK2,-18.3,22.7,35.2,29.8,400,30,50,jak2_pocket_007.png,方位角超出0-360范围
`;
