const QUEUE_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  WAITING_RETRY: 'WAITING_RETRY',
  WAITING_MANUAL: 'WAITING_MANUAL',
  FAILED_PERMANENT: 'FAILED_PERMANENT',
  MANUAL_HANDLING: 'MANUAL_HANDLING',
  COMPENSATED: 'COMPENSATED',
  CLOSED: 'CLOSED'
};

const STATUS_LABELS = {
  [QUEUE_STATUS.PENDING]: '待处理',
  [QUEUE_STATUS.PROCESSING]: '处理中',
  [QUEUE_STATUS.WAITING_RETRY]: '等待重试',
  [QUEUE_STATUS.WAITING_MANUAL]: '等待人工',
  [QUEUE_STATUS.FAILED_PERMANENT]: '永久失败',
  [QUEUE_STATUS.MANUAL_HANDLING]: '人工处理中',
  [QUEUE_STATUS.COMPENSATED]: '补偿入账',
  [QUEUE_STATUS.CLOSED]: '已关闭'
};

const ACTIONS = {
  SUBMIT: 'SUBMIT',
  PROCESS: 'PROCESS',
  RETRY: 'RETRY',
  MANUAL_TAKEOVER: 'MANUAL_TAKEOVER',
  COMPENSATE: 'COMPENSATE',
  CLOSE: 'CLOSE',
  FAIL: 'FAIL'
};

const SOURCE_TYPES = {
  IMPLANT_BATCH: 'IMPLANT_BATCH',
  APPOINTMENT: 'APPOINTMENT',
  SUPPLIER_INVOICE: 'SUPPLIER_INVOICE',
  SUPPLIER_STATEMENT: 'SUPPLIER_STATEMENT',
  APPROVAL_EMAIL: 'APPROVAL_EMAIL'
};

const MATERIAL_TYPES = {
  IMPLANT: 'IMPLANT',
  ABUTMENT: 'ABUTMENT',
  CROWN: 'CROWN',
  OTHER: 'OTHER'
};

module.exports = {
  QUEUE_STATUS,
  STATUS_LABELS,
  ACTIONS,
  SOURCE_TYPES,
  MATERIAL_TYPES
};
