DEMO_PAYLOAD = {
    "source_file": "2026年6月溶出实验汇总_旧表.xlsx",
    "imported_by": "张工",
    "remark": "本月第二批，含上月遗留数据补录",
    "samples": [
        {
            "sample_no": "S001",
            "product_name": "阿司匹林肠溶片",
            "batch_number": "B20260512",
            "test_date": "2026-06-08",
            "analyst": "李明",
            "weighing_value": 0.1023,
            "weighing_unit": "g",
            "medium": "0.1mol/L 盐酸",
            "temperature": 37.0,
            "rotation_speed": 100,
            "time_points": [5, 10, 15, 30, 45, 60],
            "dissolution_data": [12.5, 28.3, 45.1, 72.8, 86.4, 92.1],
            "spectrum_data": [
                {"time_point": 5, "peaks": [{"retention_time": 3.21, "area": 125000}]},
                {"time_point": 10, "peaks": [{"retention_time": 3.24, "area": 280000}]},
                {"time_point": 15, "peaks": [{"retention_time": 3.22, "area": 420000}, {"retention_time": 3.23, "area": 380000}, {"retention_time": 4.10, "area": 15000}]},
                {"time_point": 30, "peaks": [{"retention_time": 3.22, "area": 720000}]},
            ],
            "temperature_curve": [
                {"time_min": 0, "temperature_c": 37.0},
                {"time_min": 5, "temperature_c": 37.1},
                {"time_min": 10, "temperature_c": 37.0},
                {"time_min": 15, "temperature_c": 36.9},
                {"time_min": 30, "temperature_c": 37.0},
                {"time_min": 45, "temperature_c": 37.1},
                {"time_min": 60, "temperature_c": 37.0},
            ],
            "old_format": False,
            "fill_remark": None,
        },
        {
            "sample_no": "S002",
            "product_name": "阿司匹林肠溶片",
            "batch_number": "B20260512",
            "test_date": "2026-06-08",
            "analyst": "李明",
            "weighing_value": 99,
            "weighing_unit": "mg",
            "medium": "0.1mol/L 盐酸",
            "temperature": 37.0,
            "rotation_speed": 100,
            "time_points": [5, 10, 15, 30, 45, 60],
            "dissolution_data": [10.2, 25.7, 42.3, 70.1, 84.5, 91.0],
            "spectrum_data": [
                {"time_point": 5, "peaks": [{"retention_time": 3.20, "area": 100000}]},
                {"time_point": 10, "peaks": [{"retention_time": 3.22, "area": 250000}]},
                {"time_point": 15, "peaks": [{"retention_time": 3.23, "area": 420000}, {"retention_time": 3.24, "area": 380000}]},
            ],
            "temperature_curve": [
                {"time_min": 0, "temperature_c": 37.0},
                {"time_min": 5, "temperature_c": 36.2, "is_anomaly": 1, "anomaly_note": "水浴升温慢"},
                {"time_min": 10, "temperature_c": 36.4, "is_anomaly": 1, "anomaly_note": "持续偏低"},
                {"time_min": 15, "temperature_c": 36.7},
                {"time_min": 30, "temperature_c": 37.0},
                {"time_min": 45, "temperature_c": 38.2, "is_anomaly": 1, "anomaly_note": "温度探头漂移疑似"},
                {"time_min": 60, "temperature_c": 37.1},
            ],
            "old_format": False,
            "fill_remark": None,
        },
        {
            "sample_no": "S003",
            "product_name": "布洛芬缓释胶囊",
            "batch_number": "B20260428",
            "test_date": "2026-05-20",
            "analyst": "王芳",
            "weighing_value": 0.305,
            "weighing_unit": "g",
            "medium": "pH6.8 磷酸盐缓冲液",
            "temperature": 37.0,
            "rotation_speed": 50,
            "time_points": [30, 60, 120, 240, 360, 480],
            "dissolution_data": [5.2, 15.8, 32.4, 55.6, 72.1, 85.3],
            "spectrum_data": [
                {"time_point": 30, "peaks": [{"retention_time": 5.10, "area": 52000}]},
                {"time_point": 60, "peaks": [{"retention_time": 5.12, "area": 158000}]},
            ],
            "temperature_curve": [
                {"time_min": 0, "temperature_c": 37.0},
                {"time_min": 120, "temperature_c": 37.0},
                {"time_min": 240, "temperature_c": 37.0},
                {"time_min": 480, "temperature_c": 37.0},
            ],
            "old_format": True,
            "fill_remark": "5月份遗留数据，6月9日补录，原始记录编号LAB-2026-0520",
        },
        {
            "sample_no": "S004",
            "product_name": "对乙酰氨基酚片",
            "batch_number": "",
            "test_date": "",
            "analyst": "",
            "weighing_value": 500,
            "weighing_unit": None,
            "medium": "水",
            "temperature": None,
            "rotation_speed": 75,
            "time_points": [10, 20, 30, 45, 60],
            "dissolution_data": [35.0, 62.0, 80.0, 90.5, 95.2],
            "spectrum_data": None,
            "temperature_curve": [],
            "old_format": True,
            "fill_remark": "2025年底旧表导入，部分字段当时未要求填写",
        },
    ],
}
