from __future__ import annotations

from datetime import date, datetime

from models import CaseStatus, DischargeCase, DRGGroup, NoteChange


def load_sample_groups() -> dict[str, DRGGroup]:
    return {
        "DRG-A01": DRGGroup(
            group_code="DRG-A01",
            group_name="肺炎伴合并症与伴随病",
            mdc="MDC-04",
            adrg="A01",
            standard_cost=18500.0,
            weight=1.23,
            is_surgical=False,
        ),
        "DRG-B12": DRGGroup(
            group_code="DRG-B12",
            group_name="冠脉搭桥术伴合并症",
            mdc="MDC-05",
            adrg="B12",
            standard_cost=62000.0,
            weight=4.10,
            is_surgical=True,
        ),
        "DRG-C03": DRGGroup(
            group_code="DRG-C03",
            group_name="胆囊切除术不伴合并症",
            mdc="MDC-06",
            adrg="C03",
            standard_cost=12800.0,
            weight=0.85,
            is_surgical=True,
        ),
        "DRG-D08": DRGGroup(
            group_code="DRG-D08",
            group_name="急性阑尾炎伴合并症",
            mdc="MDC-06",
            adrg="D08",
            standard_cost=9500.0,
            weight=0.63,
            is_surgical=False,
        ),
        "DRG-E15": DRGGroup(
            group_code="DRG-E15",
            group_name="脑梗死伴合并症与伴随病",
            mdc="MDC-01",
            adrg="E15",
            standard_cost=21000.0,
            weight=1.40,
            is_surgical=False,
        ),
    }


def load_sample_cases() -> dict[str, DischargeCase]:
    return {
        "CASE-001": DischargeCase(
            case_id="CASE-001",
            patient_name="张三",
            dept_code="DEPT-01",
            dept_name="心内科",
            admission_date=date(2026, 5, 10),
            discharge_date=date(2026, 5, 18),
            total_cost=21500.0,
            drg_group_code="DRG-A01",
            drg_group_name="肺炎伴合并症与伴随病",
            standard_cost=18500.0,
            actual_reimbursement=16200.0,
            status=CaseStatus.NORMAL,
            cost_items={"药品费": 8500.0, "检查费": 4200.0, "护理费": 3100.0, "材料费": 5700.0},
            created_at=datetime(2026, 5, 18, 10, 0),
        ),
        "CASE-002": DischargeCase(
            case_id="CASE-002",
            patient_name="李四",
            dept_code="DEPT-02",
            dept_name="心外科",
            admission_date=date(2026, 5, 5),
            discharge_date=date(2026, 5, 20),
            total_cost=78000.0,
            drg_group_code="DRG-B12",
            drg_group_name="冠脉搭桥术伴合并症",
            standard_cost=62000.0,
            actual_reimbursement=55000.0,
            status=CaseStatus.MISSING_FIELDS,
            missing_fields=["手术记录", "麻醉方式"],
            cost_items={"药品费": 32000.0, "检查费": 8500.0, "护理费": None, "材料费": 27500.0},
            note="护理费尚未录入，待补",
            created_at=datetime(2026, 5, 20, 14, 30),
        ),
        "CASE-003": DischargeCase(
            case_id="CASE-003",
            patient_name="王五",
            dept_code="DEPT-03",
            dept_name="普外科",
            admission_date=date(2026, 5, 12),
            discharge_date=date(2026, 5, 16),
            total_cost=10500.0,
            drg_group_code="DRG-C03",
            drg_group_name="胆囊切除术不伴合并症",
            standard_cost=12800.0,
            actual_reimbursement=10500.0,
            status=CaseStatus.LATE_SUPPLEMENT,
            supplement_date=date(2026, 5, 25),
            cost_items={"药品费": 3800.0, "检查费": 2900.0, "护理费": 1800.0, "材料费": 2000.0},
            note="出院诊断补填延迟7天，5月25日补录完成",
            note_history=[
                NoteChange(
                    old_value="",
                    new_value="出院诊断补填延迟，待补录",
                    changed_at=datetime(2026, 5, 16, 16, 0),
                    changed_by="医生赵六",
                ),
                NoteChange(
                    old_value="出院诊断补填延迟，待补录",
                    new_value="出院诊断补填延迟7天，5月25日补录完成",
                    changed_at=datetime(2026, 5, 25, 9, 30),
                    changed_by="医保办周七",
                ),
            ],
            created_at=datetime(2026, 5, 16, 16, 0),
        ),
        "CASE-004": DischargeCase(
            case_id="CASE-004",
            patient_name="孙八",
            dept_code="DEPT-03",
            dept_name="普外科",
            admission_date=date(2026, 5, 8),
            discharge_date=date(2026, 5, 13),
            total_cost=14200.0,
            drg_group_code="DRG-D08",
            drg_group_name="急性阑尾炎伴合并症",
            original_drg_group_code="DRG-C03",
            standard_cost=9500.0,
            actual_reimbursement=8200.0,
            status=CaseStatus.NOTE_MODIFIED,
            cost_items={"药品费": 4100.0, "检查费": 3200.0, "护理费": 2600.0, "材料费": None},
            note="初始分组DRG-C03，经核查重分为DRG-D08。材料费缺项待补。",
            note_history=[
                NoteChange(
                    old_value="",
                    new_value="初始分组DRG-C03，费用正常",
                    changed_at=datetime(2026, 5, 13, 11, 0),
                    changed_by="系统自动",
                ),
                NoteChange(
                    old_value="初始分组DRG-C03，费用正常",
                    new_value="初始分组DRG-C03，经核查重分为DRG-D08",
                    changed_at=datetime(2026, 5, 15, 10, 0),
                    changed_by="医保办吴九",
                ),
                NoteChange(
                    old_value="初始分组DRG-C03，经核查重分为DRG-D08",
                    new_value="初始分组DRG-C03，经核查重分为DRG-D08。材料费缺项待补。",
                    changed_at=datetime(2026, 5, 20, 14, 0),
                    changed_by="财务郑十",
                ),
            ],
            created_at=datetime(2026, 5, 13, 11, 0),
        ),
        "CASE-005": DischargeCase(
            case_id="CASE-005",
            patient_name="钱十一",
            dept_code="DEPT-04",
            dept_name="神经内科",
            admission_date=date(2026, 5, 1),
            discharge_date=date(2026, 5, 22),
            total_cost=28500.0,
            drg_group_code="DRG-E15",
            drg_group_name="脑梗死伴合并症与伴随病",
            standard_cost=21000.0,
            actual_reimbursement=None,
            status=CaseStatus.MISSING_FIELDS,
            missing_fields=["报销金额"],
            cost_items={"药品费": 12000.0, "检查费": 6500.0, "护理费": 5200.0, "材料费": None},
            note="报销金额未到账，材料费缺项",
            created_at=datetime(2026, 5, 22, 9, 0),
        ),
    }
