import React, { useState } from 'react';
import type { TreatmentOpinion } from '@/types';
import { Section } from '@/components/ui/Section';
import { Button } from '@/components/ui/Button';
import { MessageSquare, Bot, User, Paperclip, Send, Clock, Sparkles } from 'lucide-react';
import { formatDateTime, formatFileSize } from '@/utils/format';

interface TreatmentOpinionProps {
  opinions: TreatmentOpinion[];
  onAdd?: (content: string) => void;
}

export const TreatmentOpinionView: React.FC<TreatmentOpinionProps> = ({ opinions, onAdd }) => {
  const [newContent, setNewContent] = useState('');
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);

  const handleSubmit = () => {
    if (!newContent.trim() || !onAdd) return;
    onAdd(newContent.trim());
    setNewContent('');
  };

  return (
    <Section
      tone="default"
      title={
        <div className="flex items-center gap-2">
          <MessageSquare className="w-4 h-4 text-primary-600" />
          <span>处理意见区</span>
          <span className="text-[11px] text-gray-400 font-normal">
            ({opinions.length} 条记录)
          </span>
        </div>
      }
      subtitle="自动诊断建议 + 人工编辑，历史时间线完整保留"
    >
      <div className="space-y-3 mb-4">
        {opinions.length === 0 ? (
          <div className="p-6 text-center text-gray-400 border-2 border-dashed border-gray-200">
            暂无处理意见，可点击下方按钮自动生成诊断建议
          </div>
        ) : (
          opinions.map((op, idx) => {
            const isAuto = op.autoGenerated;
            return (
              <div
                key={op.id}
                className={[
                  'border-2 p-3 relative',
                  isAuto
                    ? 'border-primary-200 bg-primary-50/40'
                    : 'border-gray-200 bg-white',
                ].join(' ')}
              >
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-primary-500 to-primary-300" />
                <div className="flex items-start gap-3">
                  <div
                    className={[
                      'w-8 h-8 flex-shrink-0 flex items-center justify-center border-2',
                      isAuto
                        ? 'bg-gradient-to-br from-primary-500 to-violet-500 text-white border-primary-400'
                        : 'bg-gray-100 text-gray-700 border-gray-300',
                    ].join(' ')}
                  >
                    {isAuto ? <Bot className="w-4 h-4" /> : <User className="w-4 h-4" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-2 mb-1.5">
                      <div className="flex items-center gap-2 min-w-0">
                        <span className="font-semibold text-sm text-gray-900">
                          {op.author}
                        </span>
                        {isAuto ? (
                          <span className="inline-flex items-center gap-0.5 text-[10px] px-1.5 py-0.5 bg-gradient-to-r from-primary-100 to-violet-100 text-primary-700 border border-primary-200">
                            <Sparkles className="w-2.5 h-2.5" />
                            自动诊断
                          </span>
                        ) : (
                          <span className="text-[10px] px-1.5 py-0.5 bg-gray-100 text-gray-600 border border-gray-200">
                            {op.authorRole}
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-1 text-[11px] text-gray-500 flex-shrink-0">
                        <Clock className="w-3 h-3" />
                        <span className="font-mono">{formatDateTime(op.createTime)}</span>
                      </div>
                    </div>
                    <div className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
                      {op.content}
                    </div>
                    {op.attachments && op.attachments.length > 0 && (
                      <div className="mt-2 pt-2 border-t border-gray-100">
                        <div className="text-[10px] font-semibold text-gray-500 mb-1 flex items-center gap-1">
                          <Paperclip className="w-2.5 h-2.5" />
                          附件 ({op.attachments.length})
                        </div>
                        <div className="flex flex-wrap gap-1.5">
                          {op.attachments.map((att, i) => (
                            <button
                              key={i}
                              className="inline-flex items-center gap-1.5 px-2 py-1 text-[11px] bg-gray-50 hover:bg-gray-100 text-gray-700 border border-gray-200 transition-colors"
                            >
                              <Paperclip className="w-3 h-3 text-gray-400" />
                              <span className="font-mono">{att.name}</span>
                              <span className="text-gray-400">({formatFileSize(att.size)})</span>
                            </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      <div className="border-2 border-gray-200 bg-gray-50/40 p-3">
        <div className="flex items-center justify-between gap-2 mb-2">
          <span className="text-xs font-semibold text-gray-600 flex items-center gap-1">
            <User className="w-3.5 h-3.5" />
            新增处理意见
          </span>
          <Button
            variant="secondary"
            size="sm"
            icon={<Sparkles className="w-3.5 h-3.5" />}
            loading={isAutoGenerating}
            onClick={() => {
              setIsAutoGenerating(true);
              setTimeout(() => {
                setNewContent(
                  '## 复核结论\n\n经过重复运行验证、补录交叉校验，结合人工终审：\n\n- [x] 异常根因确认，非程序问题\n- [x] 不影响生产链路，风险可控\n- [ ] 需纳入下一轮巡检任务（下周）\n\n**终审建议**：\n标记为"已确认"，结论记录已归档。'
                );
                setIsAutoGenerating(false);
              }, 800);
            }}
          >
            一键生成建议
          </Button>
        </div>
        <textarea
          value={newContent}
          onChange={(e) => setNewContent(e.target.value)}
          placeholder="输入处理意见，支持 Markdown 格式..."
          className="w-full min-h-[80px] p-2.5 text-sm border border-gray-300 focus:outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 font-mono resize-y bg-white"
        />
        <div className="flex items-center justify-between mt-2">
          <div className="text-[11px] text-gray-400 flex items-center gap-3">
            <span className="flex items-center gap-1">
              <Paperclip className="w-3 h-3" />
              可上传附件（支持 .txt / .sql / .log）
            </span>
          </div>
          <Button
            variant="primary"
            size="sm"
            icon={<Send className="w-3.5 h-3.5" />}
            onClick={handleSubmit}
            disabled={!newContent.trim()}
          >
            提交意见
          </Button>
        </div>
      </div>
    </Section>
  );
};
