const CONFIG = {
  CANVAS_WIDTH: 1200,
  CANVAS_HEIGHT: 700,
  GRID_SIZE: 50,
  PATH_WIDTH: 60,
  TOWER_RANGE: 120,
  TOWER_ATTACK_SPEED: 1000,
  ENEMY_BASE_SPEED: 0.8,
  TICK_RATE: 16,
  RHYTHM_WINDOW: 80,
  PERFECT_WINDOW: 30,
  GOOD_WINDOW: 60,
  MISS_WINDOW: 100,
  SCORE_PERFECT: 100,
  SCORE_GOOD: 50,
  SCORE_MISS: -30,
  SPEED_DRIFT_THRESHOLD: 5,
  VERSION: '1.0.0',
  DATA_SOURCE: 'drum-track-rehearsal-v1',
};

const TOWER_TYPES = {
  ACCENT: {
    id: 'accent',
    name: '重音塔',
    cost: 100,
    damage: 25,
    range: 140,
    color: '#FF6B6B',
    icon: '💥',
    description: '攻击重音节拍的怪物，对强拍伤害翻倍',
    targetPattern: ['accent', 'strong'],
  },
  SYNCOPATION: {
    id: 'syncopation',
    name: '切分塔',
    cost: 120,
    damage: 20,
    range: 130,
    color: '#4ECDC4',
    icon: '⚡',
    description: '攻击切分节拍的怪物，对弱拍伤害加成',
    targetPattern: ['syncopation', 'weak'],
  },
  STABLE: {
    id: 'stable',
    name: '稳定塔',
    cost: 80,
    damage: 15,
    range: 160,
    color: '#95E1D3',
    icon: '🛡️',
    description: '攻击所有节拍，维持稳定节奏，防止速度漂移',
    targetPattern: ['all'],
    antiDrift: true,
  },
  FILL: {
    id: 'fill',
    name: '加花塔',
    cost: 150,
    damage: 35,
    range: 100,
    color: '#DDA0DD',
    icon: '🎯',
    description: '高伤害但攻击速度慢，针对加花段落',
    targetPattern: ['fill'],
    attackSpeed: 1500,
  },
};

const ENEMY_TYPES = {
  BASIC: {
    id: 'basic',
    name: '基础节拍怪',
    hp: 50,
    speed: 1,
    reward: 20,
    color: '#FFE66D',
    beatType: 'normal',
  },
  ACCENT: {
    id: 'accent',
    name: '重音怪',
    hp: 80,
    speed: 0.8,
    reward: 35,
    color: '#FF6B6B',
    beatType: 'accent',
  },
  SYNCOPATION: {
    id: 'syncopation',
    name: '切分怪',
    hp: 60,
    speed: 1.3,
    reward: 30,
    color: '#4ECDC4',
    beatType: 'syncopation',
  },
  FAST: {
    id: 'fast',
    name: '快拍怪',
    hp: 40,
    speed: 1.8,
    reward: 25,
    color: '#FF8C42',
    beatType: 'fast',
  },
  DRIFT: {
    id: 'drift',
    name: '漂移怪',
    hp: 70,
    speed: 1.0,
    reward: 40,
    color: '#9B59B6',
    beatType: 'drift',
    causesDrift: true,
  },
};

const RHYTHM_ERROR_TYPES = {
  EARLY: {
    id: 'early',
    name: '抢拍',
    description: '击打比节拍早',
    penalty: 0.8,
    color: '#E74C3C',
  },
  LATE: {
    id: 'late',
    name: '拖拍',
    description: '击打比节拍晚',
    penalty: 0.8,
    color: '#F39C12',
  },
  MISS: {
    id: 'miss',
    name: '漏拍',
    description: '完全漏掉的节拍',
    penalty: 0.5,
    color: '#7F8C8D',
  },
  WEAK_ACCENT: {
    id: 'weak_accent',
    name: '重音不足',
    description: '重音节拍没有足够力度',
    penalty: 0.7,
    color: '#E67E22',
  },
  SPEED_DRIFT: {
    id: 'speed_drift',
    name: '速度漂移',
    description: '整体速度偏离目标BPM',
    penalty: 0.6,
    color: '#9B59B6',
  },
};
