const WAVE_STATUS = {
  CREATED: 'CREATED',
  PICKING: 'PICKING',
  REVIEWING: 'REVIEWING',
  SHORTAGE: 'SHORTAGE',
  REPLENISHING: 'REPLENISHING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const REPLENISHMENT_STATUS = {
  PENDING: 'PENDING',
  PICKING: 'PICKING',
  PARTIAL: 'PARTIAL',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

const LOCATION_OCCUPATION_STATUS = {
  OCCUPIED: 'OCCUPIED',
  RELEASED: 'RELEASED'
};

const PERFORMANCE_TYPE = {
  PICKING: 'PICKING',
  REPLENISHMENT: 'REPLENISHMENT',
  REVIEW: 'REVIEW'
};

const OPERATION_TYPE = {
  CREATE_WAVE: 'CREATE_WAVE',
  UPDATE_WAVE: 'UPDATE_WAVE',
  MARK_SHORTAGE: 'MARK_SHORTAGE',
  CREATE_REPLENISHMENT: 'CREATE_REPLENISHMENT',
  CONFIRM_REPLENISHMENT: 'CONFIRM_REPLENISHMENT',
  RELEASE_LOCATION: 'RELEASE_LOCATION',
  RECALCULATE_PERFORMANCE: 'RECALCULATE_PERFORMANCE',
  CREATE_APPEAL: 'CREATE_APPEAL',
  REVIEW_APPEAL: 'REVIEW_APPEAL',
  CORRECT_SHORTAGE: 'CORRECT_SHORTAGE'
};

const APPEAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const DIFF_TYPE = {
  SHORTAGE: 'SHORTAGE',
  OVERPICK: 'OVERPICK',
  WRONG_SKU: 'WRONG_SKU'
};

const SHORTAGE_REASON = {
  INVENTORY_SHORTAGE: 'INVENTORY_SHORTAGE',
  LOCATION_ERROR: 'LOCATION_ERROR',
  SKU_DAMAGE: 'SKU_DAMAGE',
  PICKER_ERROR: 'PICKER_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  OTHER: 'OTHER'
};

const WAVE_STATUS_TRANSITIONS = {
  [WAVE_STATUS.CREATED]: [WAVE_STATUS.PICKING, WAVE_STATUS.CANCELLED],
  [WAVE_STATUS.PICKING]: [WAVE_STATUS.REVIEWING, WAVE_STATUS.SHORTAGE],
  [WAVE_STATUS.REVIEWING]: [WAVE_STATUS.SHORTAGE, WAVE_STATUS.COMPLETED],
  [WAVE_STATUS.SHORTAGE]: [WAVE_STATUS.REPLENISHING, WAVE_STATUS.COMPLETED],
  [WAVE_STATUS.REPLENISHING]: [WAVE_STATUS.COMPLETED, WAVE_STATUS.SHORTAGE],
  [WAVE_STATUS.COMPLETED]: [],
  [WAVE_STATUS.CANCELLED]: []
};

const REPLENISHMENT_STATUS_TRANSITIONS = {
  [REPLENISHMENT_STATUS.PENDING]: [REPLENISHMENT_STATUS.PICKING, REPLENISHMENT_STATUS.CANCELLED],
  [REPLENISHMENT_STATUS.PICKING]: [REPLENISHMENT_STATUS.PARTIAL, REPLENISHMENT_STATUS.COMPLETED, REPLENISHMENT_STATUS.FAILED],
  [REPLENISHMENT_STATUS.PARTIAL]: [REPLENISHMENT_STATUS.COMPLETED, REPLENISHMENT_STATUS.FAILED],
  [REPLENISHMENT_STATUS.COMPLETED]: [],
  [REPLENISHMENT_STATUS.FAILED]: [],
  [REPLENISHMENT_STATUS.CANCELLED]: []
};

module.exports = {
  WAVE_STATUS,
  REPLENISHMENT_STATUS,
  LOCATION_OCCUPATION_STATUS,
  PERFORMANCE_TYPE,
  OPERATION_TYPE,
  APPEAL_STATUS,
  DIFF_TYPE,
  SHORTAGE_REASON,
  WAVE_STATUS_TRANSITIONS,
  REPLENISHMENT_STATUS_TRANSITIONS
};
