STATUS_REVIEWING = "reviewing"
STATUS_PENDING = "pending"
STATUS_APPROVED = "approved"
STATUS_REJECTED = "rejected"
STATUS_FAILED = "failed"

STATUS_LABELS = {
    STATUS_REVIEWING: "待判断",
    STATUS_PENDING: "待确认",
    STATUS_APPROVED: "可放行",
    STATUS_REJECTED: "需补材料",
    STATUS_FAILED: "失败",
}

DECISION_APPROVE = "approve"
DECISION_REJECT = "reject"

DECISION_LABELS = {
    DECISION_APPROVE: "放行",
    DECISION_REJECT: "补材料",
}

ERROR_RUN_ID_DUPLICATE = "E001"
ERROR_RUN_NOT_FOUND = "E002"
ERROR_INVALID_STATUS = "E003"
ERROR_SNAPSHOT_EMPTY = "E004"
ERROR_CONFLICT_UNRESOLVED = "E005"

ERROR_MESSAGES = {
    ERROR_RUN_ID_DUPLICATE: "运行编号重复，已挂起待确认",
    ERROR_RUN_NOT_FOUND: "未找到对应的运行记录",
    ERROR_INVALID_STATUS: "状态不合法",
    ERROR_SNAPSHOT_EMPTY: "特征快照为空",
    ERROR_CONFLICT_UNRESOLVED: "存在未解决的冲突，请先处理",
}
