#!/bin/bash
cd "$(dirname "$0")"
echo "========================================"
echo "  AB实验成本看板 - 启动脚本"
echo "========================================"
echo ""
echo "📋 交付说明:"
echo "   训练负责人老周可通过以下方式核对数据:"
echo "   1. 训练日志 → 详情页'数据来源'标签"
echo "   2. 处理记录 → 详情页'概览'标签 + 状态历史"
echo "   3. 接口返回 → 详情页'接口返回'标签 或 /api/records/{run_id}/export"
echo ""
echo "🔍 核心功能:"
echo "   ✓ 公式透明: 展示公式、单位、边界值、计算过程"
echo "   ✓ 来源可追: 保留原始字段、映射关系、来源文件"
echo "   ✓ 状态清晰: 已处理/待确认/待补证据 一目了然"
echo "   ✓ 灰度可查: 拆分为样本/阈值/人工改判三类"
echo "   ✓ Run_id查重: 自动检测重复并触发人工确认"
echo ""
echo "🌐 访问地址: http://localhost:8000"
echo "📚 API文档:  http://localhost:8000/docs"
echo ""
echo "按 Ctrl+C 停止服务"
echo "========================================"
echo ""

python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000
