import { Berth, Material, Operation, ErrorRecord, CanvasState } from '../types';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();

export const mockBerths: Berth[] = [
  {
    id: 'berth-001',
    name: '1号泊位',
    x: 60, y: 60, width: 180, height: 100,
    status: 'occupied',
    shipName: '远洋一号',
    eta: daysAgo(2),
    etd: hoursAgo(6),
    cargoType: '集装箱',
    materialIds: ['mat-001', 'mat-004'],
    remark: '旧表数据，注意单位换算',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: 'berth-002',
    name: '2号泊位',
    x: 280, y: 60, width: 200, height: 100,
    status: 'available',
    materialIds: [],
    remark: '',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  {
    id: 'berth-003',
    name: '3号泊位',
    x: 520, y: 60, width: 220, height: 100,
    status: 'occupied',
    shipName: '港达八号',
    eta: daysAgo(1),
    etd: hoursAgo(24),
    cargoType: '散货',
    materialIds: ['mat-002'],
    remark: '补录备注：坐标存在翻转嫌疑',
    hasError: true,
    errorType: 'coordinate_flip',
    createdAt: daysAgo(15),
    updatedAt: hoursAgo(18),
  },
  {
    id: 'berth-004',
    name: '4号泊位',
    x: 60, y: 220, width: 160, height: 100,
    status: 'maintenance',
    materialIds: ['mat-003'],
    remark: '维护中，预计3天后恢复',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: 'berth-005',
    name: '5号泊位',
    x: 260, y: 220, width: 240, height: 100,
    status: 'occupied',
    shipName: '东方之星',
    eta: hoursAgo(48),
    etd: hoursAgo(12),
    cargoType: '液体散货',
    materialIds: [],
    remark: '',
    createdAt: daysAgo(12),
    updatedAt: hoursAgo(36),
  },
  {
    id: 'berth-006',
    name: '6号泊位',
    x: 540, y: 220, width: 200, height: 100,
    status: 'available',
    materialIds: [],
    remark: '漏填单位，待补充',
    createdAt: daysAgo(12),
    updatedAt: hoursAgo(30),
  },
  {
    id: 'berth-007',
    name: '7号泊位',
    x: 60, y: 380, width: 200, height: 100,
    status: 'occupied',
    shipName: '蓝鲸二号',
    eta: hoursAgo(36),
    etd: hoursAgo(4),
    cargoType: '集装箱',
    materialIds: ['mat-005', 'mat-006'],
    remark: '比例尺错用警告',
    hasError: true,
    errorType: 'scale_mismatch',
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'berth-008',
    name: '8号泊位',
    x: 300, y: 380, width: 180, height: 100,
    status: 'available',
    materialIds: [],
    remark: '',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'berth-009',
    name: '9号泊位',
    x: 520, y: 380, width: 220, height: 100,
    status: 'maintenance',
    materialIds: [],
    remark: '旧表遗留泊位，数据待校验',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    id: 'berth-010',
    name: '10号泊位',
    x: 60, y: 540, width: 680, height: 80,
    status: 'available',
    materialIds: [],
    remark: '大型泊位，多船停靠',
    createdAt: daysAgo(20),
    updatedAt: hoursAgo(40),
  },
];

export const mockMaterials: Material[] = [
  {
    id: 'mat-001',
    title: '1号泊位调度截图_20240601',
    type: 'screenshot',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aerial%20view%20of%20container%20port%20with%20cargo%20ships%20docked%20at%20industrial%20harbor%20blue%20toned&image_size=landscape_4_3',
    annotations: [
      { id: 'ann-001', type: 'rect', x: 50, y: 80, width: 120, height: 60, color: '#E67E22', author: '张主管', createdAt: daysAgo(5) },
      { id: 'ann-002', type: 'text', x: 55, y: 85, text: '注意：此处吃水深度标注异常', color: '#E67E22', author: '张主管', createdAt: daysAgo(5) },
    ],
    comments: [
      { id: 'c-001', content: '该截图来自旧系统导出，坐标单位可能是英尺而非米，请核实。', author: '李工', createdAt: daysAgo(4) },
      { id: 'c-002', content: '补录意见：经核对，确实存在单位混淆问题，后续调度按米制修正。', author: '张主管', createdAt: daysAgo(3), isSupplementary: true },
    ],
    tags: ['截图', '旧系统', '单位问题'],
    source: '旧调度系统导出',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'mat-002',
    title: '3号泊位坐标标注草稿',
    type: 'draft',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=handwritten%20engineering%20draft%20paper%20with%20harbor%20layout%20grid%20coordinates%20technical%20drawing%20blueprint%20style&image_size=landscape_4_3',
    annotations: [
      { id: 'ann-003', type: 'arrow', x: 200, y: 100, width: 80, height: 50, color: '#E74C3C', author: '王工', createdAt: daysAgo(3) },
      { id: 'ann-004', type: 'text', x: 290, y: 95, text: 'X/Y疑似翻转！', color: '#E74C3C', author: '王工', createdAt: daysAgo(3) },
    ],
    comments: [
      { id: 'c-003', content: '草稿显示坐标有问题，南北方向和东西方向对调了。', author: '王工', createdAt: daysAgo(3) },
    ],
    tags: ['草稿', '坐标翻转', '手绘'],
    source: '现场手工草图扫描',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'mat-003',
    title: '4号泊位维修通知',
    type: 'opinion',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=maintenance%20notice%20document%20with%20orange%20warning%20stripes%20industrial%20safety%20sign%20harbor%20equipment%20repair&image_size=landscape_4_3',
    annotations: [],
    comments: [
      { id: 'c-004', content: '4号泊位由于岸桥设备故障，暂停作业3天，维修队已进场。', author: '陈主管', createdAt: daysAgo(2) },
      { id: 'c-005', content: '请调度室将原计划停靠船舶临时调配至其他泊位。', author: '陈主管', createdAt: daysAgo(2) },
    ],
    tags: ['维修', '通知'],
    source: '生产部',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mat-004',
    title: '1号泊位装船进度表_补录',
    type: 'screenshot',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=spreadsheet%20cargo%20loading%20progress%20table%20industrial%20logistics%20data%20grid%20blue%20gray%20style&image_size=landscape_4_3',
    annotations: [
      { id: 'ann-005', type: 'circle', x: 300, y: 150, width: 40, height: 40, color: '#E67E22', author: '张主管', createdAt: daysAgo(1) },
    ],
    comments: [
      { id: 'c-006', content: '补录：进度表第三列单位漏填，应为"吨"而非"箱"。', author: '张主管', createdAt: daysAgo(1), isSupplementary: true },
    ],
    tags: ['补录', '进度表', '漏填单位'],
    source: '补录材料',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mat-005',
    title: '7号泊位比例尺参考图',
    type: 'draft',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=engineering%20scale%20ruler%20measurement%20reference%20technical%20drawing%20blueprint%20harbor%20map%20grid&image_size=landscape_4_3',
    annotations: [
      { id: 'ann-006', type: 'text', x: 100, y: 50, text: '比例尺：1cm = 50m（旧版1cm=100m错用！）', color: '#E74C3C', author: '赵工', createdAt: hoursAgo(12) },
    ],
    comments: [
      { id: 'c-007', content: '旧版参考图标注比例尺错误，导致7号泊位尺寸被标注为实际的两倍。', author: '赵工', createdAt: hoursAgo(12) },
    ],
    tags: ['比例尺', '错误', '参考图'],
    source: '设计院旧版参考',
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(10),
  },
  {
    id: 'mat-006',
    title: '7号泊位现场确认照片',
    type: 'screenshot',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=harbor%20dock%20close%20up%20photograph%20container%20cranes%20blue%20sky%20cargo%20ship%20industrial%20port&image_size=landscape_4_3',
    annotations: [
      { id: 'ann-007', type: 'rect', x: 50, y: 50, width: 200, height: 150, color: '#27AE60', author: '张主管', createdAt: hoursAgo(6) },
    ],
    comments: [
      { id: 'c-008', content: '人工确认：现场照片核实泊位尺寸已修正，蓝鲸二号靠泊正常。', author: '张主管', createdAt: hoursAgo(6) },
    ],
    tags: ['现场照片', '人工确认'],
    source: '现场拍摄',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
];

export const mockOperations: Operation[] = [
  {
    id: 'op-001',
    type: 'create',
    timestamp: daysAgo(10),
    operator: '张主管',
    description: '导入旧表：创建1-10号泊位（旧系统数据）',
    beforeState: null,
    afterState: { count: 10 },
    isSupplementary: false,
    isConfirmed: true,
    confirmedBy: '张主管',
    confirmedAt: daysAgo(10),
  },
  {
    id: 'op-002',
    type: 'move',
    timestamp: daysAgo(8),
    operator: '李工',
    description: '调整3号泊位位置',
    berthId: 'berth-003',
    beforeState: { x: 480, y: 60 },
    afterState: { x: 520, y: 60 },
    materialId: 'mat-002',
    isError: true,
    errorType: 'coordinate_flip',
    errorReason: '使用了坐标翻转的草稿素材，X/Y方向疑似对调',
    comment: '移动时未核对坐标系方向',
    isConfirmed: false,
  },
  {
    id: 'op-003',
    type: 'status_change',
    timestamp: daysAgo(5),
    operator: '陈主管',
    description: '4号泊位状态变更为维护中',
    berthId: 'berth-004',
    beforeState: { status: 'available' },
    afterState: { status: 'maintenance' },
    materialId: 'mat-003',
    isConfirmed: true,
    confirmedBy: '陈主管',
    confirmedAt: daysAgo(5),
  },
  {
    id: 'op-004',
    type: 'move',
    timestamp: daysAgo(4),
    operator: '王工',
    description: '调整7号泊位位置和尺寸（比例尺错用）',
    berthId: 'berth-007',
    beforeState: { x: 80, y: 400, width: 100, height: 50 },
    afterState: { x: 60, y: 380, width: 200, height: 100 },
    materialId: 'mat-005',
    isError: true,
    errorType: 'scale_mismatch',
    errorReason: '参考图比例尺为1cm=100m（应为50m），导致泊位尺寸翻倍',
    comment: '引用了错误比例尺的旧版参考图',
    isConfirmed: false,
  },
  {
    id: 'op-005',
    type: 'annotate',
    timestamp: daysAgo(3),
    operator: '张主管',
    description: '在1号泊位截图上标注单位问题',
    materialId: 'mat-001',
    beforeState: { annotations: 0 },
    afterState: { annotations: 2 },
    isConfirmed: true,
    confirmedBy: '张主管',
    confirmedAt: daysAgo(3),
  },
  {
    id: 'op-006',
    type: 'zoom',
    timestamp: daysAgo(2),
    operator: '李工',
    description: '缩放画布至150%（改变判断）',
    beforeState: { zoom: 1 },
    afterState: { zoom: 1.5 },
    comment: '缩放后发现泊位间距异常，疑似坐标问题',
    isConfirmed: true,
    confirmedBy: '李工',
    confirmedAt: daysAgo(2),
  },
  {
    id: 'op-007',
    type: 'pan',
    timestamp: daysAgo(2),
    operator: '李工',
    description: '平移画布查看东北区域',
    beforeState: { panX: 0, panY: 0 },
    afterState: { panX: -80, panY: -40 },
    isConfirmed: true,
    confirmedBy: '李工',
    confirmedAt: daysAgo(2),
  },
  {
    id: 'op-008',
    type: 'status_change',
    timestamp: daysAgo(1),
    operator: '张主管',
    description: '补录：7号泊位状态变更为已靠泊',
    berthId: 'berth-007',
    beforeState: { status: 'available' },
    afterState: { status: 'occupied' },
    materialId: 'mat-006',
    isSupplementary: true,
    comment: '补录昨日蓝鲸二号靠泊记录',
    isConfirmed: true,
    confirmedBy: '张主管',
    confirmedAt: hoursAgo(20),
  },
  {
    id: 'op-009',
    type: 'move',
    timestamp: hoursAgo(8),
    operator: '赵工',
    description: '微调5号泊位位置',
    berthId: 'berth-005',
    beforeState: { x: 270, y: 220 },
    afterState: { x: 260, y: 220 },
    isConfirmed: true,
    confirmedBy: '赵工',
    confirmedAt: hoursAgo(8),
  },
  {
    id: 'op-010',
    type: 'annotate',
    timestamp: hoursAgo(6),
    operator: '张主管',
    description: '人工确认：7号泊位照片标注正常区域',
    materialId: 'mat-006',
    beforeState: { annotations: 0 },
    afterState: { annotations: 1 },
    isConfirmed: true,
    confirmedBy: '张主管',
    confirmedAt: hoursAgo(6),
  },
];

export const mockErrors: ErrorRecord[] = [
  {
    id: 'err-001',
    operationId: 'op-002',
    errorType: '坐标翻转',
    errorPosition: { x: 520, y: 60 },
    errorReason: '草稿素材mat-002中X/Y坐标标注方向对调，导致3号泊位位置被错误移动',
    materialId: 'mat-002',
    suggestion: '核对标准坐标系（北向为Y正方向），重新校准3号泊位坐标',
    createdAt: daysAgo(7),
  },
  {
    id: 'err-002',
    operationId: 'op-004',
    errorType: '比例尺错用',
    errorPosition: { x: 60, y: 380 },
    errorReason: '参考素材mat-005为旧版参考图，标注比例尺1cm=100m，实际应为1cm=50m，导致7号泊位尺寸标注为实际值两倍',
    materialId: 'mat-005',
    suggestion: '使用最新版设计院图纸(2024.05版)，重新按1:50比例尺标注泊位尺寸',
    createdAt: daysAgo(4),
  },
  {
    id: 'err-003',
    operationId: 'op-001',
    errorType: '漏填单位',
    errorPosition: { x: 540, y: 220 },
    errorReason: '6号泊位从旧系统导入时，载重单位字段为空，来源为mat-001旧表数据',
    materialId: 'mat-001',
    suggestion: '补录缺失单位：最大载重吨位为50000DWT',
    createdAt: daysAgo(10),
  },
];

export const defaultCanvasState: CanvasState = {
  zoom: 1,
  panX: 0,
  panY: 0,
  selectedId: null,
  tool: 'select',
  scale: 50,
  scaleUnit: 'm',
  isCoordinateFlipped: false,
};

export const currentUser = {
  name: '张主管',
  role: 'supervisor' as 'supervisor' | 'student',
};
