import type { Anomaly, Annotation, AuthorizationNote, ChangeRecord, AlignmentItem } from "@/types";

const now = new Date();
const iso = (offset: number) => new Date(now.getTime() - offset * 60000).toISOString();

export const initialAnomalies: Anomaly[] = [
  {
    id: "ANM-001",
    channel: "CH1-主唱",
    session: "北京站-2026-06-13",
    status: "pending",
    value: 0.87,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: true,
    boundaryReason: "电平值 0.87 落在阈值区间 [0.75, 0.90] 内，距上界仅 0.03。此类边界样本在历史数据中约有 40% 为误报，但同时也有 35% 在下一场次升级为确认异常。因此此样本对'是否需更换耳返驱动单元'的结论有决定性影响：纳入则建议更换，排除则维持现状。",
    originalJudgment: "建议更换驱动单元",
    currentJudgment: "建议更换驱动单元",
  },
  {
    id: "ANM-002",
    channel: "CH3-吉他",
    session: "北京站-2026-06-13",
    status: "confirmed",
    value: 0.95,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: false,
    boundaryReason: "",
    originalJudgment: "确认异常，需检修",
    currentJudgment: "确认异常，需检修",
  },
  {
    id: "ANM-003",
    channel: "CH5-和声1",
    session: "北京站-2026-06-13",
    status: "pending",
    value: 0.78,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: true,
    boundaryReason: "电平值 0.78 刚越过阈值下界 0.75，属于临界触发。此样本影响了'本轮巡检是否需要全线复测'的结论——若排除此样本，复测范围从全线缩减为单通道；若纳入，则触发全线复测流程。",
    originalJudgment: "触发全线复测",
    currentJudgment: "触发全线复测",
  },
  {
    id: "ANM-004",
    channel: "CH2-贝斯",
    session: "上海站-2026-06-10",
    status: "overridden",
    value: 0.82,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: true,
    boundaryReason: "电平值 0.82 在阈值区间中段，但频响曲线在该通道 2kHz-4kHz 出现异常凹陷。边界样本本身不构成硬性异常，但频响特征与上次检修前一致，此样本对'是否提前维护'的结论有参考权重。",
    originalJudgment: "建议提前维护",
    currentJudgment: "继续观察（人工覆盖）",
  },
  {
    id: "ANM-005",
    channel: "CH7-键盘",
    session: "上海站-2026-06-10",
    status: "confirmed",
    value: 0.92,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: false,
    boundaryReason: "",
    originalJudgment: "确认异常，需检修",
    currentJudgment: "确认异常，需检修",
  },
  {
    id: "ANM-006",
    channel: "CH4-鼓组",
    session: "广州站-2026-06-07",
    status: "pending",
    value: 0.76,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: true,
    boundaryReason: "电平值 0.76 仅超出阈值 0.01，属于极度临界。此样本决定了'广州站是否需追加返场检测'——排除则无需返场，纳入则需安排。历史上同级别临界样本有 60% 在后续场次确认异常。",
    originalJudgment: "建议追加返场检测",
    currentJudgment: "建议追加返场检测",
  },
  {
    id: "ANM-007",
    channel: "CH6-和声2",
    session: "广州站-2026-06-07",
    status: "confirmed",
    value: 0.93,
    threshold: 0.75,
    thresholdUpper: 0.90,
    isBoundary: false,
    boundaryReason: "",
    originalJudgment: "确认异常，需检修",
    currentJudgment: "确认异常，需检修",
  },
];

export const initialAnnotations: Annotation[] = [
  {
    id: "ANN-001",
    anomalyId: "ANM-004",
    content: "贝斯手反馈该通道音质正常，2kHz-4kHz凹陷为混响补偿所致，非硬件问题",
    author: "录音师老许",
    impactScope: ["SH-2026-bass-track.wav", "曲目表-上海站", "最后清单-CH2"],
    sourceLine: "ANM-004 / L42",
    createdAt: iso(120),
  },
];

export const initialAuthorizationNotes: AuthorizationNote[] = [];

export const initialChangeRecords: ChangeRecord[] = [
  {
    id: "CHR-001",
    type: "override",
    description: "CH2-贝斯判断由'建议提前维护'覆盖为'继续观察'",
    impactScope: ["SH-2026-bass-track.wav", "曲目表-上海站", "最后清单-CH2"],
    sourceLine: "ANM-004 / L42",
    author: "录音师老许",
    beforeValue: "建议提前维护",
    afterValue: "继续观察（人工覆盖）",
    createdAt: iso(120),
  },
];

export const initialAlignmentItems: AlignmentItem[] = [
  {
    id: "ALI-001",
    fileName: "BJ-2026-vocal-track.wav",
    trackName: "曲目表-北京站 / CH1-主唱",
    checklistEntry: "最后清单-CH1: 电平复检",
    alignmentStatus: "aligned",
    note: "",
  },
  {
    id: "ALI-002",
    fileName: "BJ-2026-guitar-track.wav",
    trackName: "曲目表-北京站 / CH3-吉他",
    checklistEntry: "最后清单-CH3: 确认检修",
    alignmentStatus: "aligned",
    note: "",
  },
  {
    id: "ALI-003",
    fileName: "SH-2026-bass-track.wav",
    trackName: "曲目表-上海站 / CH2-贝斯",
    checklistEntry: "最后清单-CH2: 人工覆盖",
    alignmentStatus: "offset",
    note: "人工批注覆盖后，曲目表备注未同步更新",
  },
  {
    id: "ALI-004",
    fileName: "SH-2026-keys-track.wav",
    trackName: "曲目表-上海站 / CH7-键盘",
    checklistEntry: "最后清单-CH7: 确认检修",
    alignmentStatus: "aligned",
    note: "",
  },
  {
    id: "ALI-005",
    fileName: "GZ-2026-drums-track.wav",
    trackName: "曲目表-广州站 / CH4-鼓组",
    checklistEntry: "最后清单-CH4: 待追加返场检测",
    alignmentStatus: "offset",
    note: "待确认是否追加返场，文件已归档但清单未闭环",
  },
  {
    id: "ALI-006",
    fileName: "GZ-2026-vocal2-track.wav",
    trackName: "曲目表-广州站 / CH6-和声2",
    checklistEntry: "最后清单-CH6: 确认检修",
    alignmentStatus: "aligned",
    note: "",
  },
  {
    id: "ALI-007",
    fileName: "BJ-2026-harmony1-track.wav",
    trackName: "曲目表-北京站 / CH5-和声1",
    checklistEntry: "最后清单-CH5: 待全线复测",
    alignmentStatus: "offset",
    note: "边界样本未确认，复测范围未定",
  },
];
