import type { Run } from '@/types'

const now = new Date()
const d = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 3600000).toISOString()

export const seedData: Run[] = [
  {
    run_id: 'RUN-20240315-001',
    status: 'completed',
    scenario_type: 'smooth',
    created_at: d(48),
    updated_at: d(46),
    stages: [
      {
        id: 's1-1',
        run_id: 'RUN-20240315-001',
        stage_name: '候选集召回',
        order: 1,
        data: { recall_count: 12000, cost_per_item: 0.003 },
        has_param_change: false,
        recorded_at: d(48),
      },
      {
        id: 's1-2',
        run_id: 'RUN-20240315-001',
        stage_name: '粗排过滤',
        order: 2,
        data: { filtered_count: 4500, cost_per_item: 0.005 },
        has_param_change: false,
        recorded_at: d(47.5),
      },
      {
        id: 's1-3',
        run_id: 'RUN-20240315-001',
        stage_name: '精排打分',
        order: 3,
        data: { scored_count: 800, cost_per_item: 0.012 },
        has_param_change: false,
        recorded_at: d(47),
      },
      {
        id: 's1-4',
        run_id: 'RUN-20240315-001',
        stage_name: '最终输出',
        order: 4,
        data: { output_count: 120, cost_per_item: 0.08 },
        has_param_change: false,
        recorded_at: d(46.5),
      },
    ],
    notes: [
      {
        id: 'n1-1',
        run_id: 'RUN-20240315-001',
        stage_id: null,
        content: '全阶段数据完整，参数无变化，结论一次填写。',
        is_supplementary: false,
        linked_conclusion_id: 'c1',
        created_at: d(46),
      },
    ],
    conclusion: {
      id: 'c1',
      run_id: 'RUN-20240315-001',
      content: '本轮召回漏斗成本正常，总成本约 9.6 元，各阶段效率达标。',
      linked_note_ids: ['n1-1'],
      created_at: d(46),
      updated_at: d(46),
    },
    screenshots: [],
    grayscale_results: [],
    confirmation_records: [],
  },
  {
    run_id: 'RUN-20240315-002',
    status: 'completed',
    scenario_type: 'supplementary',
    created_at: d(24),
    updated_at: d(22),
    stages: [
      {
        id: 's2-1',
        run_id: 'RUN-20240315-002',
        stage_name: '候选集召回',
        order: 1,
        data: { recall_count: 15000, cost_per_item: 0.003 },
        has_param_change: false,
        recorded_at: d(24),
      },
      {
        id: 's2-2',
        run_id: 'RUN-20240315-002',
        stage_name: '粗排过滤',
        order: 2,
        data: { filtered_count: 5200, cost_per_item: 0.005 },
        has_param_change: false,
        recorded_at: d(23.5),
      },
      {
        id: 's2-3',
        run_id: 'RUN-20240315-002',
        stage_name: '精排打分',
        order: 3,
        data: { scored_count: 950, cost_per_item: 0.015 },
        has_param_change: true,
        recorded_at: d(23),
      },
      {
        id: 's2-4',
        run_id: 'RUN-20240315-002',
        stage_name: '最终输出',
        order: 4,
        data: { output_count: 130, cost_per_item: 0.09 },
        has_param_change: false,
        recorded_at: d(22.5),
      },
    ],
    notes: [
      {
        id: 'n2-1',
        run_id: 'RUN-20240315-002',
        stage_id: 's2-3',
        content: '精排阶段阈值参数变化漏记，原始阈值 0.5 调整为 0.45，cost_per_item 从 0.012 涨到 0.015。',
        is_supplementary: true,
        linked_conclusion_id: 'c2',
        created_at: d(22.2),
      },
      {
        id: 'n2-2',
        run_id: 'RUN-20240315-002',
        stage_id: null,
        content: '后补：阈值变化导致精排成本上升 25%，但输出质量提升明显。',
        is_supplementary: true,
        linked_conclusion_id: 'c2',
        created_at: d(22),
      },
    ],
    conclusion: {
      id: 'c2',
      run_id: 'RUN-20240315-002',
      content: '本轮精排阈值从 0.5 调至 0.45，成本上升 25%，输出质量提升。总成本约 14.0 元，需关注阈值调整对成本的影响。',
      linked_note_ids: ['n2-1', 'n2-2'],
      created_at: d(22.5),
      updated_at: d(22),
    },
    screenshots: [
      {
        id: 'ss2-1',
        run_id: 'RUN-20240315-002',
        note_id: 'n2-1',
        image_data: '',
        description: '精排阈值调整前后对比截图',
        created_at: d(22.1),
      },
    ],
    grayscale_results: [],
    confirmation_records: [],
  },
  {
    run_id: 'RUN-20240315-003',
    status: 'pending_confirmation',
    scenario_type: 'exception',
    created_at: d(4),
    updated_at: d(2),
    stages: [
      {
        id: 's3-1',
        run_id: 'RUN-20240315-003',
        stage_name: '候选集召回',
        order: 1,
        data: { recall_count: 10000, cost_per_item: 0.003 },
        has_param_change: false,
        recorded_at: d(4),
      },
      {
        id: 's3-2',
        run_id: 'RUN-20240315-003',
        stage_name: '粗排过滤',
        order: 2,
        data: { filtered_count: 3800, cost_per_item: 0.005 },
        has_param_change: false,
        recorded_at: d(3.5),
      },
    ],
    notes: [
      {
        id: 'n3-1',
        run_id: 'RUN-20240315-003',
        stage_id: null,
        content: 'run_id 重复卡，上次运行数据已存在，需人工确认是否合并数据。',
        is_supplementary: false,
        linked_conclusion_id: null,
        created_at: d(2),
      },
    ],
    conclusion: null,
    screenshots: [],
    grayscale_results: [],
    confirmation_records: [
      {
        id: 'cr3-1',
        run_id: 'RUN-20240315-003',
        reason: '检测到 run_id RUN-20240315-003 已存在历史数据',
        next_step: '选择合并（保留历史备注追加新数据）或覆盖（清空重新开始）',
        action_taken: null,
        created_at: d(2),
      },
    ],
  },
  {
    run_id: 'RUN-20240315-004',
    status: 'completed',
    scenario_type: 'supplementary',
    created_at: d(8),
    updated_at: d(6),
    stages: [
      {
        id: 's4-1',
        run_id: 'RUN-20240315-004',
        stage_name: '候选集召回',
        order: 1,
        data: { recall_count: 18000, cost_per_item: 0.004 },
        has_param_change: false,
        recorded_at: d(8),
      },
      {
        id: 's4-2',
        run_id: 'RUN-20240315-004',
        stage_name: '粗排过滤',
        order: 2,
        data: { filtered_count: 6000, cost_per_item: 0.006 },
        has_param_change: false,
        recorded_at: d(7.5),
      },
      {
        id: 's4-3',
        run_id: 'RUN-20240315-004',
        stage_name: '精排打分',
        order: 3,
        data: { scored_count: 1100, cost_per_item: 0.013 },
        has_param_change: true,
        recorded_at: d(7),
      },
      {
        id: 's4-4',
        run_id: 'RUN-20240315-004',
        stage_name: '最终输出',
        order: 4,
        data: { output_count: 180, cost_per_item: 0.085 },
        has_param_change: false,
        recorded_at: d(6.5),
      },
    ],
    notes: [
      {
        id: 'n4-1',
        run_id: 'RUN-20240315-004',
        stage_id: 's4-3',
        content: '灰度测试阶段，样本量从 10000 扩大到 18000。',
        is_supplementary: false,
        linked_conclusion_id: 'c4',
        created_at: d(7),
      },
    ],
    conclusion: {
      id: 'c4',
      run_id: 'RUN-20240315-004',
      content: '灰度测试完成，样本扩大后总成本约 18.5 元，需关注阈值调整和人工改判的影响。',
      linked_note_ids: ['n4-1'],
      created_at: d(6.5),
      updated_at: d(6),
    },
    screenshots: [
      {
        id: 'ss4-1',
        run_id: 'RUN-20240315-004',
        note_id: null,
        image_data: '',
        description: '灰度测试整体漏斗对比截图',
        created_at: d(6.2),
      },
    ],
    grayscale_results: [
      {
        id: 'gr4-1',
        run_id: 'RUN-20240315-004',
        dimension: 'sample_change',
        before: { sample_size: 10000, recall_cost: 0.003 },
        after: { sample_size: 18000, recall_cost: 0.004 },
        change_desc: '样本量扩大 80%，单条召回成本从 0.003 升至 0.004',
      },
      {
        id: 'gr4-2',
        run_id: 'RUN-20240315-004',
        dimension: 'threshold_change',
        before: { threshold: 0.5, precision: 0.72 },
        after: { threshold: 0.42, precision: 0.68 },
        change_desc: '阈值从 0.5 降至 0.42，精确率下降 4% 但召回率提升',
      },
      {
        id: 'gr4-3',
        run_id: 'RUN-20240315-004',
        dimension: 'manual_override',
        before: { auto_count: 120, manual_count: 0 },
        after: { auto_count: 158, manual_count: 22 },
        change_desc: '人工改判 22 条，改判率 12.2%，主要集中于边界案例',
      },
      {
        id: 'gr4-4',
        run_id: 'RUN-20240315-004',
        dimension: 'manual_override',
        before: { auto_approved: 95, auto_rejected: 25 },
        after: { auto_approved: 88, auto_rejected: 32 },
        change_desc: '5 条自动通过改判为拒绝，3 条自动拒绝改判为通过',
      },
    ],
    confirmation_records: [],
  },
]
