import {
  SourceMaterial,
  TrainingSample,
  ModelVersion,
  BoundaryCase,
  ReviewReport,
  GrayscaleComparison,
  GroupMetric,
} from './types';

export const sourceMaterials: SourceMaterial[] = [
  {
    id: 'src-001',
    name: '风控样本旧表_2024Q1.xlsx',
    type: 'old_table',
    location: '//10.20.30.40/share/legacy/风控样本旧表_2024Q1.xlsx',
    lastModified: '2024-03-28 15:42',
    owner: '李明（已离职）',
  },
  {
    id: 'src-002',
    name: '安全规则_v3.2.docx',
    type: 'shared_drive',
    location: '共享盘/安全组/规则文档/安全规则_v3.2.docx',
    lastModified: '2024-05-12 09:18',
    owner: '张伟',
  },
  {
    id: 'src-003',
    name: '评测题库_金融风控_500题.xlsx',
    type: 'evaluation_question_bank',
    location: '知识库/评测/金融风控评测题库_500题.xlsx',
    lastModified: '2024-06-03 14:05',
    owner: '王芳',
  },
  {
    id: 'src-004',
    name: '人工标注补录备注_20240520.txt',
    type: 'supplementary_note',
    location: '临时文件夹/标注补录/人工标注补录备注_20240520.txt',
    lastModified: '2024-05-20 18:33',
    owner: '赵磊',
  },
  {
    id: 'src-005',
    name: '人工修正工单_R20240610.xlsx',
    type: 'manual_correction',
    location: '工单系统/导出/人工修正工单_R20240610.xlsx',
    lastModified: '2024-06-10 11:27',
    owner: '陈静',
  },
];

export const trainingSamples: TrainingSample[] = [
  {
    id: 's-0001',
    sampleNo: 'FIN-RISK-0001',
    content: '用户近30天交易金额：50000',
    label: 'negative',
    originalLabel: 'negative',
    status: 'train',
    sourceMaterialId: 'src-001',
    sourceRow: 3,
    groupKey: 'g-trade-amt',
    unit: '元',
    rawValue: '50000',
    normalizedValue: '50000',
    manualCorrections: [],
    annotations: ['旧表原始数据'],
    createdAt: '2024-04-02 10:12',
    updatedAt: '2024-04-02 10:12',
    appearsInSets: ['train-v1', 'train-v2'],
  },
  {
    id: 's-0002',
    sampleNo: 'FIN-RISK-0002',
    content: '用户近30天交易笔数：128，异地登录次数：3',
    label: 'positive',
    originalLabel: 'positive',
    status: 'train',
    sourceMaterialId: 'src-001',
    sourceRow: 4,
    groupKey: 'g-login-abnormal',
    rawValue: '128/3',
    normalizedValue: '交易笔数:128, 异地登录:3',
    manualCorrections: [],
    annotations: ['旧表原始数据'],
    createdAt: '2024-04-02 10:13',
    updatedAt: '2024-04-02 10:13',
    appearsInSets: ['train-v1', 'train-v2'],
  },
  {
    id: 's-0003',
    sampleNo: 'FIN-RISK-0003',
    content: '单笔交易金额：8600',
    label: 'positive',
    originalLabel: 'negative',
    status: 'duplicate',
    sourceMaterialId: 'src-001',
    sourceRow: 156,
    groupKey: 'g-trade-amt',
    unit: '元',
    rawValue: '8600',
    normalizedValue: '8600',
    manualCorrections: [
      {
        id: 'cor-001',
        timestamp: '2024-05-20 18:35',
        operator: '赵磊',
        field: 'label',
        oldValue: 'negative',
        newValue: 'positive',
        reason: '补录备注：该笔交易为异常套现特征（见备注第3条）',
        source: 'src-004',
      },
    ],
    annotations: ['旧表重复样本', '补录备注修正标签'],
    createdAt: '2024-04-02 11:02',
    updatedAt: '2024-05-20 18:35',
    flagged: true,
    flagReason: '脏样本：与s-0004内容一致但标签矛盾',
    duplicatesOf: 's-0004',
    appearsInSets: ['train-v1', 'train-v2', 'val-v1'],
  },
  {
    id: 's-0004',
    sampleNo: 'FIN-RISK-0003-dup',
    content: '单笔交易金额：8600',
    label: 'negative',
    originalLabel: 'negative',
    status: 'duplicate',
    sourceMaterialId: 'src-003',
    sourceRow: 87,
    groupKey: 'g-trade-amt',
    unit: '元',
    rawValue: '8600',
    normalizedValue: '8600',
    manualCorrections: [],
    annotations: ['评测题库导出'],
    createdAt: '2024-06-03 14:20',
    updatedAt: '2024-06-03 14:20',
    appearsInSets: ['test-v1', 'val-v1'],
  },
  {
    id: 's-0005',
    sampleNo: 'FIN-RISK-0005',
    content: '用户月收入：12000',
    label: 'negative',
    originalLabel: 'positive',
    status: 'dirty',
    sourceMaterialId: 'src-001',
    sourceRow: 78,
    groupKey: 'g-income',
    rawValue: '12000',
    normalizedValue: '12000',
    manualCorrections: [
      {
        id: 'cor-002',
        timestamp: '2024-06-10 10:55',
        operator: '陈静',
        field: 'label',
        oldValue: 'positive',
        newValue: 'negative',
        reason: '原标注错误，用户月收入12000不属于高风险',
        source: 'src-005',
      },
    ],
    annotations: ['旧表原始标注错误', '人工修正工单修正'],
    createdAt: '2024-04-02 15:48',
    updatedAt: '2024-06-10 10:55',
    appearsInSets: ['train-v1', 'train-v2', 'val-v1'],
  },
  {
    id: 's-0006',
    sampleNo: 'FIN-RISK-0006',
    content: '近7天申请贷款次数：',
    label: 'neutral',
    originalLabel: 'negative',
    status: 'dirty',
    sourceMaterialId: 'src-001',
    sourceRow: 201,
    groupKey: 'g-loan-inquiry',
    rawValue: '（空）',
    normalizedValue: '缺失',
    manualCorrections: [],
    annotations: ['旧表数据缺失', '漏填：7天申贷次数单位为"次"', '未填数字'],
    createdAt: '2024-04-03 09:22',
    updatedAt: '2024-05-20 18:40',
    flagged: true,
    flagReason: '脏样本：字段值缺失，人工备注提到漏填单位',
    appearsInSets: ['train-v1', 'train-v2'],
  },
  {
    id: 's-0007',
    sampleNo: 'FIN-RISK-0007',
    content: '征信逾期次数：2，负债收入比：0.65',
    label: 'positive',
    originalLabel: 'positive',
    status: 'leak',
    sourceMaterialId: 'src-001',
    sourceRow: 56,
    groupKey: 'g-credit',
    rawValue: '2/0.65',
    normalizedValue: '逾期次数:2, 负债收入比:0.65',
    manualCorrections: [],
    annotations: ['训练验证泄漏'],
    createdAt: '2024-04-02 14:30',
    updatedAt: '2024-04-02 14:30',
    appearsInSets: ['train-v1', 'val-v1', 'test-v1'],
  },
  {
    id: 's-0008',
    sampleNo: 'FIN-RISK-0008',
    content: '设备指纹异常标记：是，设备ID：DEV-8821',
    label: 'positive',
    originalLabel: 'uncertain',
    status: 'train',
    sourceMaterialId: 'src-003',
    sourceRow: 201,
    groupKey: 'g-device-fingerprint',
    rawValue: '是/DEV-8821',
    normalizedValue: '指纹异常:是, 设备ID:DEV-8821',
    manualCorrections: [
      {
        id: 'cor-003',
        timestamp: '2024-05-20 18:50',
        operator: '赵磊',
        field: 'label',
        oldValue: 'uncertain',
        newValue: 'positive',
        reason: '补录：根据安全规则v3.2第4.2节判定为正样本',
        source: 'src-004',
      },
    ],
    annotations: ['评测题库数据', '补录备注引用安全规则'],
    createdAt: '2024-06-03 15:10',
    updatedAt: '2024-06-05 09:30',
    appearsInSets: ['train-v1', 'train-v2'],
  },
  {
    id: 's-0009',
    sampleNo: 'FIN-RISK-0009',
    content: '近30天交易金额：50000',
    label: 'negative',
    originalLabel: 'negative',
    status: 'test',
    sourceMaterialId: 'src-003',
    sourceRow: 305,
    groupKey: 'g-trade-amt',
    unit: '元',
    rawValue: '50000',
    normalizedValue: '50000',
    manualCorrections: [],
    annotations: ['评测题库测试集样本'],
    createdAt: '2024-06-03 16:02',
    updatedAt: '2024-06-03 16:02',
    appearsInSets: ['test-v1'],
  },
  {
    id: 's-0010',
    sampleNo: 'FIN-RISK-0010',
    content: '用户年龄：28，学历：本科，月收入：25000',
    label: 'negative',
    originalLabel: 'negative',
    status: 'val',
    sourceMaterialId: 'src-003',
    sourceRow: 412,
    groupKey: 'g-demographics',
    rawValue: '28/本科/25000',
    normalizedValue: '年龄:28, 学历:本科, 月收入:25000',
    manualCorrections: [],
    annotations: ['评测题库验证集'],
    createdAt: '2024-06-03 16:45',
    updatedAt: '2024-06-03 16:45',
    appearsInSets: ['val-v1'],
  },
  {
    id: 's-0011',
    sampleNo: 'FIN-RISK-0011',
    content: '单日转账金额：58000',
    label: 'positive',
    originalLabel: 'negative',
    status: 'dirty',
    sourceMaterialId: 'src-001',
    sourceRow: 334,
    groupKey: 'g-transfer',
    rawValue: '5.8',
    normalizedValue: '58000',
    manualCorrections: [
      {
        id: 'cor-004',
        timestamp: '2024-06-10 11:15',
        operator: '陈静',
        field: 'rawValue',
        oldValue: '5.8',
        newValue: '58000',
        reason: '旧表单位为万元，漏填单位；原标注5.8误判为5.8元，实际为5.8万元=58000元',
        source: 'src-005',
      },
      {
        id: 'cor-005',
        timestamp: '2024-06-10 11:15',
        operator: '陈静',
        field: 'label',
        oldValue: 'negative',
        newValue: 'positive',
        reason: '数值修正后重新判定',
        source: 'src-005',
      },
    ],
    annotations: ['旧表漏填单位', '原单位万元误写5.8实际5.8万元'],
    createdAt: '2024-04-03 11:50',
    updatedAt: '2024-06-10 11:15',
    flagged: true,
    flagReason: '脏样本：漏填单位导致数值错误进而标签错误',
    appearsInSets: ['train-v1', 'train-v2'],
  },
  {
    id: 's-0012',
    sampleNo: 'FIN-RISK-0012',
    content: '近90天被拒贷次数：1次',
    label: 'positive',
    originalLabel: 'positive',
    status: 'train',
    sourceMaterialId: 'src-003',
    sourceRow: 178,
    groupKey: 'g-loan-reject',
    unit: '次',
    rawValue: '1',
    normalizedValue: '1',
    manualCorrections: [],
    annotations: ['评测题库样本'],
    createdAt: '2024-06-03 14:55',
    updatedAt: '2024-06-03 14:55',
    appearsInSets: ['train-v1', 'train-v2', 'val-v1'],
  },
];

const buildGroupMetricsV1 = (): GroupMetric[] => [
  {
    groupKey: 'g-trade-amt',
    groupName: '交易金额组',
    totalSamples: 4,
    positiveCount: 1,
    negativeCount: 3,
    neutralCount: 0,
    precision: 0.82,
    recall: 0.78,
    f1: 0.8,
    accuracy: 0.75,
    sampleIds: ['s-0001', 's-0003', 's-0004', 's-0009'],
  },
  {
    groupKey: 'g-login-abnormal',
    groupName: '登录异常组',
    totalSamples: 1,
    positiveCount: 1,
    negativeCount: 0,
    neutralCount: 0,
    precision: 0.9,
    recall: 0.85,
    f1: 0.87,
    accuracy: 0.88,
    sampleIds: ['s-0002'],
  },
  {
    groupKey: 'g-income',
    groupName: '收入组',
    totalSamples: 2,
    positiveCount: 0,
    negativeCount: 2,
    neutralCount: 0,
    precision: 0.7,
    recall: 0.72,
    f1: 0.71,
    accuracy: 0.7,
    sampleIds: ['s-0005', 's-0010'],
  },
  {
    groupKey: 'g-loan-inquiry',
    groupName: '贷款查询组',
    totalSamples: 1,
    positiveCount: 0,
    negativeCount: 0,
    neutralCount: 1,
    precision: 0.5,
    recall: 0.5,
    f1: 0.5,
    accuracy: 0.5,
    sampleIds: ['s-0006'],
  },
  {
    groupKey: 'g-credit',
    groupName: '征信组',
    totalSamples: 1,
    positiveCount: 1,
    negativeCount: 0,
    neutralCount: 0,
    precision: 0.85,
    recall: 0.82,
    f1: 0.83,
    accuracy: 0.85,
    sampleIds: ['s-0007'],
  },
  {
    groupKey: 'g-device-fingerprint',
    groupName: '设备指纹组',
    totalSamples: 1,
    positiveCount: 1,
    negativeCount: 0,
    neutralCount: 0,
    precision: 0.88,
    recall: 0.9,
    f1: 0.89,
    accuracy: 0.88,
    sampleIds: ['s-0008'],
  },
  {
    groupKey: 'g-demographics',
    groupName: '人口统计组',
    totalSamples: 1,
    positiveCount: 0,
    negativeCount: 1,
    neutralCount: 0,
    precision: 0.92,
    recall: 0.9,
    f1: 0.91,
    accuracy: 0.92,
    sampleIds: ['s-0010'],
  },
  {
    groupKey: 'g-transfer',
    groupName: '转账组',
    totalSamples: 1,
    positiveCount: 0,
    negativeCount: 1,
    neutralCount: 0,
    precision: 0.6,
    recall: 0.55,
    f1: 0.57,
    accuracy: 0.5,
    sampleIds: ['s-0011'],
  },
  {
    groupKey: 'g-loan-reject',
    groupName: '拒贷组',
    totalSamples: 1,
    positiveCount: 1,
    negativeCount: 0,
    neutralCount: 0,
    precision: 0.8,
    recall: 0.78,
    f1: 0.79,
    accuracy: 0.8,
    sampleIds: ['s-0012'],
  },
];

const buildGroupMetricsV2 = (): GroupMetric[] => {
  const v1 = buildGroupMetricsV1();
  return v1.map((g) => {
    if (g.groupKey === 'g-trade-amt') {
      return { ...g, accuracy: 0.6, precision: 0.68, recall: 0.65, f1: 0.66 };
    }
    if (g.groupKey === 'g-income') {
      return { ...g, accuracy: 0.85, precision: 0.82, recall: 0.83, f1: 0.83 };
    }
    if (g.groupKey === 'g-transfer') {
      return { ...g, accuracy: 0.88, precision: 0.85, recall: 0.86, f1: 0.86, positiveCount: 1, negativeCount: 0 };
    }
    return g;
  });
};

export const modelVersions: ModelVersion[] = [
  {
    id: 'v-20240402-staging',
    versionName: 'v1.0.0-staging',
    createdAt: '2024-04-02 16:30',
    createdBy: '算法-刘洋',
    status: 'staging',
    description: '首个基于旧表数据初版模型',
    trainSampleCount: 8,
    valSampleCount: 3,
    testSampleCount: 2,
    overallAccuracy: 0.76,
    overallPrecision: 0.74,
    overallRecall: 0.72,
    overallF1: 0.73,
    sampleChanges: [],
    groupMetrics: buildGroupMetricsV1(),
    flaggedSamples: [],
  },
  {
    id: 'v-20240520-grayscale',
    versionName: 'v1.1.0-grayscale',
    createdAt: '2024-05-20 19:10',
    createdBy: '算法-刘洋',
    status: 'grayscale',
    parentVersionId: 'v-20240402-staging',
    description: '合并补录备注修正3条，修复部分标签',
    trainSampleCount: 9,
    valSampleCount: 3,
    testSampleCount: 2,
    overallAccuracy: 0.78,
    overallPrecision: 0.77,
    overallRecall: 0.75,
    overallF1: 0.76,
    sampleChanges: [
      { sampleId: 's-0003', field: 'label', oldValue: 'negative', newValue: 'positive', changeType: 'changed', affectsJudgment: true },
      { sampleId: 's-0008', field: 'label', oldValue: 'uncertain', newValue: 'positive', changeType: 'changed', affectsJudgment: true },
      { sampleId: 's-0006', field: 'annotations', oldValue: '（空）', newValue: '漏填：7天申贷次数单位为"次"', changeType: 'added', affectsJudgment: false },
    ],
    groupMetrics: buildGroupMetricsV1(),
    flaggedSamples: ['s-0003', 's-0006'],
    grayscalePercent: 10,
    grayscaleStartAt: '2024-05-21 09:00',
  },
  {
    id: 'v-20240605-production',
    versionName: 'v1.1.0-production',
    createdAt: '2024-06-05 10:00',
    createdBy: '算法-刘洋',
    status: 'production',
    parentVersionId: 'v-20240520-grayscale',
    description: '灰度验证通过，全量上线',
    trainSampleCount: 9,
    valSampleCount: 3,
    testSampleCount: 2,
    overallAccuracy: 0.78,
    overallPrecision: 0.77,
    overallRecall: 0.75,
    overallF1: 0.76,
    sampleChanges: [],
    groupMetrics: buildGroupMetricsV1(),
    flaggedSamples: ['s-0003', 's-0006'],
    grayscalePercent: 100,
    grayscaleStartAt: '2024-05-21 09:00',
    grayscaleEndAt: '2024-06-05 10:00',
  },
  {
    id: 'v-20240610-rollback',
    versionName: 'v1.2.0-rollback',
    createdAt: '2024-06-10 14:00',
    createdBy: '算法-刘洋',
    status: 'rollback',
    parentVersionId: 'v-20240605-production',
    description: '上线2天后发现问题回滚',
    trainSampleCount: 9,
    valSampleCount: 3,
    testSampleCount: 2,
    overallAccuracy: 0.74,
    overallPrecision: 0.71,
    overallRecall: 0.7,
    overallF1: 0.7,
    sampleChanges: [
      { sampleId: 's-0011', field: 'rawValue', oldValue: '5.8', newValue: '58000', changeType: 'changed', affectsJudgment: true },
      { sampleId: 's-0011', field: 'label', oldValue: 'negative', newValue: 'positive', changeType: 'changed', affectsJudgment: true },
      { sampleId: 's-0005', field: 'label', oldValue: 'positive', newValue: 'negative', changeType: 'changed', affectsJudgment: true },
    ],
    groupMetrics: buildGroupMetricsV2(),
    flaggedSamples: ['s-0003', 's-0005', 's-0006', 's-0011'],
    rollbackReason: '发现脏样本s-0011漏填单位导致v1.2引入偏差，转账组指标异常下降，回滚至v1.1.0',
  },
  {
    id: 'v-20240612-staging-v2',
    versionName: 'v1.3.0-staging',
    createdAt: '2024-06-12 11:20',
    createdBy: '算法-刘洋',
    status: 'staging',
    parentVersionId: 'v-20240605-production',
    description: '修正脏样本，剔除泄漏样本重新训练',
    trainSampleCount: 7,
    valSampleCount: 2,
    testSampleCount: 2,
    overallAccuracy: 0.83,
    overallPrecision: 0.82,
    overallRecall: 0.81,
    overallF1: 0.81,
    sampleChanges: [
      { sampleId: 's-0007', field: 'status', oldValue: 'train', newValue: 'removed-from-train', changeType: 'removed', affectsJudgment: true },
      { sampleId: 's-0003', field: 'status', oldValue: 'duplicate', newValue: 'removed-from-train', changeType: 'removed', affectsJudgment: true },
      { sampleId: 's-0004', field: 'status', oldValue: 'duplicate', newValue: 'kept', changeType: 'unchanged', affectsJudgment: false },
    ],
    groupMetrics: buildGroupMetricsV2(),
    flaggedSamples: ['s-0005', 's-0011'],
  },
];

export const grayscaleComparison: GrayscaleComparison = {
  baseVersionId: 'v-20240605-production',
  targetVersionId: 'v-20240610-rollback',
  overallDiff: {
    accuracyDiff: -0.04,
    precisionDiff: -0.06,
    recallDiff: -0.05,
    f1Diff: -0.06,
  },
  judgmentChangedSamples: [
    {
      sampleId: 's-0011',
      baseLabel: 'negative',
      targetLabel: 'positive',
      reason: '漏填单位修正后数值从5.8→58000，阈值突破5万判定线',
      rootChangeField: 'rawValue/label',
    },
    {
      sampleId: 's-0005',
      baseLabel: 'positive',
      targetLabel: 'negative',
      reason: '人工修正工单修正了误标注',
      rootChangeField: 'label',
    },
  ],
  groupDiffs: [
    { groupKey: 'g-trade-amt', baseAccuracy: 0.75, targetAccuracy: 0.6, accuracyDiff: -0.15 },
    { groupKey: 'g-income', baseAccuracy: 0.7, targetAccuracy: 0.85, accuracyDiff: 0.15 },
    { groupKey: 'g-transfer', baseAccuracy: 0.5, targetAccuracy: 0.88, accuracyDiff: 0.38 },
  ],
};

export const boundaryCases: BoundaryCase[] = [
  {
    id: 'bc-001',
    title: '脏样本重复 · 旧表 vs 评测题库 同内容不同标签',
    description:
      '样本 FIN-RISK-0003 与 FIN-RISK-0003-dup 内容完全一致（单笔交易金额8600元），但旧表来源和评测题库来源标注矛盾。',
    category: 'dirty_duplicate',
    severity: 'high',
    beforeState: {
      sample_no: 'FIN-RISK-0003',
      source: '风控样本旧表_2024Q1.xlsx 第156行',
      content: '单笔交易金额：8600',
      label: 'positive（补录备注修正后）',
      '原始标注': 'negative',
      单位: '元',
      出现集合: 'train-v1 / train-v2 / val-v1',
    },
    afterState: {
      sample_no: 'FIN-RISK-0003-dup',
      source: '评测题库_金融风控_500题.xlsx 第87行',
      content: '单笔交易金额：8600',
      label: 'negative',
      '原始标注': 'negative',
      单位: '元',
      出现集合: 'test-v1 / val-v1',
    },
    judgmentChanged: true,
    oldJudgment: 'negative',
    newJudgment: 'positive',
    traceChain: [
      {
        stepNo: 1,
        title: '旧表导出训练样本',
        description: '从旧表第156行导出样本，原始标注为 negative',
        type: 'info',
        meta: [
          { key: '来源文件', value: '风控样本旧表_2024Q1.xlsx' },
          { key: '行号', value: '第156行' },
          { key: '样本编号', value: 'FIN-RISK-0003' },
        ],
      },
      {
        stepNo: 2,
        title: '人工补录备注覆盖标签',
        description:
          '5月20日标注同学根据"人工标注补录备注"将该样本标签由 negative 修正为 positive，理由为该笔交易符合异常套现特征',
        type: 'warning',
        meta: [
          { key: '操作人', value: '赵磊' },
          { key: '时间', value: '2024-05-20 18:35' },
          { key: '备注来源', value: '人工标注补录备注_20240520.txt' },
        ],
      },
      {
        stepNo: 3,
        title: '评测题库导出重复样本',
        description:
          '评测题库第87行存在内容完全相同的样本，标签为 negative，未同步修正',
        type: 'danger',
        meta: [
          { key: '来源文件', value: '评测题库_金融风控_500题.xlsx' },
          { key: '行号', value: '第87行' },
          { key: '样本编号', value: 'FIN-RISK-0003-dup' },
        ],
      },
      {
        stepNo: 4,
        title: '同样本跨集污染',
        description:
          '同一内容在训练集标 positive，验证集/测试集标 negative，模型在验证集上被"教错',
        type: 'danger',
        meta: [
          { key: '训练集标签', value: 'positive' },
          { key: '验证/测试集标签', value: 'negative' },
          { key: '影响', value: '该样本在验证集被错误评估为FP，拉低precision' },
        ],
      },
    ],
    materialRef: '风控样本旧表_2024Q1.xlsx + 评测题库_金融风控_500题.xlsx',
    rootCause: '补录备注只修正了旧表样本，未同步到评测题库导出的重复副本',
    impactSummary:
      '该样本在训练集中为正、验证集中为负，模型学到"学对了但评测时"被判错，precision 指标虚低 2.3%。',
  },
  {
    id: 'bc-002',
    title: '训练验证泄漏 · 样本同时出现在训练集与验证集/测试集',
    description:
      'FIN-RISK-0007（征信逾期次数：2，负债收入比：0.65）同时出现在 train-v1、val-v1、test-v1 三个集合中。',
    category: 'train_val_leak',
    severity: 'high',
    beforeState: {
      样本编号: 'FIN-RISK-0007',
      内容: '征信逾期次数：2，负债收入比：0.65',
      标签: 'positive',
      '训练集(v1)': '✓ 存在',
      '验证集(v1)': '✓ 存在',
      '测试集(v1)': '✓ 存在',
      来源: '风控样本旧表_2024Q1.xlsx 第56行',
    },
    afterState: {
      样本编号: 'FIN-RISK-0007',
      内容: '征信逾期次数：2，负债收入比：0.65',
      标签: 'positive',
      '训练集(v1.3)': '✗ 已剔除',
      '验证集(v1)': '✓ 保留',
      '测试集(v1)': '✓ 保留',
      来源: '风控样本旧表_2024Q1.xlsx 第56行',
    },
    judgmentChanged: true,
    oldJudgment: 'positive',
    newJudgment: 'positive',
    traceChain: [
      {
        stepNo: 1,
        title: '旧表随机切分',
        description: '旧表第56行样本被随机划分进训练子集',
        type: 'info',
        meta: [
          { key: '切分方式', value: '8:1:1 随机切分' },
          { key: '分配结果', value: 'train-v1' },
        ],
      },
      {
        stepNo: 2,
        title: '评测题库独立划分',
        description:
          '同一行样本（内容相同）在评测题库中被划分进入验证/测试子集',
        type: 'warning',
        meta: [
          { key: '来源', value: '评测题库_金融风控_500题.xlsx' },
          { key: '分配结果', value: 'val-v1 / test-v1' },
        ],
      },
      {
        stepNo: 3,
        title: '泄漏检测触发',
        description:
          'v1.3 版本对样本做 hash 去重，发现同一指纹重复出现在三个集合',
        type: 'danger',
        meta: [
          { key: '重复集合', value: 'train ∩ val ∩ test' },
          { key: '样本 hash', value: 'd4a56f7c' },
        ],
      },
      {
        stepNo: 4,
        title: '修正方案',
        description: '从训练集中移除该样本，仅保留在验证/测试集',
        type: 'success',
        meta: [
          { key: '修正版本', value: 'v1.3.0-staging' },
          { key: '操作时间', value: '2024-06-12 11:05' },
        ],
      },
    ],
    materialRef: '风控样本旧表_2024Q1.xlsx + 评测题库_金融风控_500题.xlsx',
    rootCause: '旧表与评测题库内容重叠，随机切分未去重',
    impactSummary:
      'v1.0~v1.2 模型评估 accuracy 被高估约 1.8%；v1.3 剔除后 accuracy 从 0.78 → 0.76，但更真实。',
  },
  {
    id: 'bc-003',
    title: '漏填单位 · 5.8万元误作5.8元，标签完全翻转',
    description:
      '旧表第334行"单日转账金额"字段单位为万元，但漏写单位，原始数值"5.8"被解读为5.8元判定负样本，实际应为5.8万元，应判正样本。',
    category: 'missing_unit',
    severity: 'high',
    beforeState: {
      样本编号: 'FIN-RISK-0010',
      字段: '单日转账金额',
      原始数值: '5.8',
      '漏填单位': '万元',
      解析值: '5.8 元',
      判定阈值: '≥ 50000 元 判 positive',
      原始标签: 'negative',
      来源: '风控样本旧表_2024Q1.xlsx 第334行',
    },
    afterState: {
      样本编号: 'FIN-RISK-0010',
      字段: '单日转账金额',
      修正数值: '58000',
      修正单位: '元',
      解析值: '58000 元',
      判定阈值: '≥ 50000 元 判 positive',
      修正标签: 'positive',
      来源: '人工修正工单_R20240610.xlsx',
    },
    judgmentChanged: true,
    oldJudgment: 'negative',
    newJudgment: 'positive',
    traceChain: [
      {
        stepNo: 1,
        title: '旧表录入',
        description:
          '旧表第334行录入"单日转账金额"列填写5.8，表头说明单位为万元但字段未写入',
        type: 'warning',
        meta: [
          { key: '来源', value: '风控样本旧表_2024Q1.xlsx' },
          { key: '行号', value: '第334行' },
          { key: '原始数值', value: '5.8' },
        ],
      },
      {
        stepNo: 2,
        title: '解析脚本误判',
        description:
          '数据解析脚本按默认单位"元"解析5.8元，低于5万元阈值',
        type: 'danger',
        meta: [
          { key: '解析结果', value: '5.8 元' },
          { key: '判定结果', value: 'negative' },
        ],
      },
      {
        stepNo: 3,
        title: '灰度异常告警',
        description:
          'v1.2 灰度期间转账组 precision 下降，人工排查发现单位缺失',
        type: 'warning',
        meta: [
          { key: '异常组', value: '转账组 g-transfer' },
          { key: 'precision 变化', value: '0.60 → 0.55' },
        ],
      },
      {
        stepNo: 4,
        title: '人工修正',
        description:
          '工单系统修正：补单位为万元，数值58000元，重新标注 positive',
        type: 'success',
        meta: [
          { key: '操作人', value: '陈静' },
          { key: '工单', value: '人工修正工单_R20240610.xlsx' },
          { key: '新标签', value: 'positive' },
        ],
      },
    ],
    materialRef: '风控样本旧表_2024Q1.xlsx + 人工修正工单_R20240610.xlsx',
    rootCause: '旧表单位说明在表头未写入字段，解析时默认单位错误',
    impactSummary:
      'v1.2 上线当天转账组 accuracy 从 0.60 骤降 0.55，触发回滚；修正后 v1.3 accuracy 恢复至 0.88。',
  },
];

export const reviewReport: ReviewReport = {
  reportId: 'REP-20240612',
  generatedAt: '2024-06-12 15:30',
  generatedBy: '算法PM-周敏',
  versionsCompared: [
    'v1.0.0-staging',
    'v1.1.0-grayscale',
    'v1.1.0-production',
    'v1.2.0-rollback',
    'v1.3.0-staging',
  ],
  summary:
    '本次评审围绕 v1.2 上线回滚事件复盘。核心问题集中在三处脏样本重复、训练验证集泄漏、漏填单位三类边界情况，共影响 5 条脏样本、1 组重复样本对、1 条泄漏样本，导致 2 次判断翻转，引发 v1.2 在转账组、交易金额组指标显著下降触发回滚。v1.3 已完成修正，建议评审通过后可进入灰度。',
  boundaryCases: boundaryCases,
  totalDirtySamples: 5,
  totalLeakSamples: 1,
  totalDuplicateGroups: 1,
  judgmentFlipCount: 2,
  recommendations: [
    '上线前强制样本去重校验：对训练/验证/测试集按内容 hash 校验，禁止跨集合重复。',
    '数值字段单位标准化：旧表数值字段必须写死单位前缀，解析脚本增加空单位告警。',
    '人工补录备注同步机制：补录备注修改须标注来源文件+行号，自动同步到所有副本。',
  ],
};
