const INVOICE_STATUS = {
  NORMAL: 'NORMAL',
  RED_INVOICED: 'RED_INVOICED',
  PAID: 'PAID',
  VOID: 'VOID',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  ADJUSTED: 'ADJUSTED',
};

const QUOTE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXECUTED: 'EXECUTED',
  CANCELLED: 'CANCELLED',
  INVALID: 'INVALID',
};

const QUOTE_STATUS_LABELS = {
  DRAFT: '草稿',
  SUBMITTED: '已提交',
  APPROVED: '已审批',
  REJECTED: '已驳回',
  EXECUTED: '已执行',
  CANCELLED: '已取消',
  INVALID: '已作废',
};

const INVOICE_STATUS_LABELS = {
  NORMAL: '正常',
  RED_INVOICED: '已红冲',
  PAID: '已付款',
  VOID: '已作废',
};

const PAYMENT_STATUS_LABELS = {
  PENDING: '待付款',
  PAID: '已付款',
  CANCELLED: '已取消',
  ADJUSTED: '已调整',
};

const OPERATION_TYPES = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  SUBMIT: 'SUBMIT',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  EXECUTE: 'EXECUTE',
  CANCEL: 'CANCEL',
  RED_INVOICE: 'RED_INVOICE',
  ADJUST: 'ADJUST',
  CALCULATE: 'CALCULATE',
};

module.exports = {
  INVOICE_STATUS,
  PAYMENT_STATUS,
  QUOTE_STATUS,
  QUOTE_STATUS_LABELS,
  INVOICE_STATUS_LABELS,
  PAYMENT_STATUS_LABELS,
  OPERATION_TYPES,
};
