import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { api } from '@/services/api';
import { useApp } from '@/context/AppContext';
import { SourceTracePanel } from './components/SourceTracePanel';
import { PermissionSnapshotView } from './components/PermissionSnapshot';
import { SchemaSnapshotView } from './components/SchemaSnapshot';
import { TreatmentOpinionView } from './components/TreatmentOpinion';
import { ReviewActions } from './components/ReviewActions';
import type {
  CallChainNode,
  PermissionSnapshot as PermissionSnapshotType,
  TableSchemaSnapshot,
  TreatmentOpinion,
  ExceptionRecord,
  ReviewActionType,
} from '@/types';
import exceptionsMock from '@/mock/exceptions.json';
import tasksMock from '@/mock/tasks.json';
import { Tag } from '@/components/ui/Tag';
import { Button } from '@/components/ui/Button';
import { ArrowLeft, AlertTriangle, Copy, Share2, ExternalLink, User } from 'lucide-react';
import {
  formatDateTime,
  getExceptionTypeLabel,
  getSeverityLabel,
  getRecordStatusLabel,
  shortId,
  getExceptionTypeColor,
  getSeverityColor,
  getRecordStatusColor,
  getStatusDotColor,
} from '@/utils/format';
import { StatusDot } from '@/components/ui/StatusDot';

const typeToneMap: Record<string, any> = {
  index_invalid: 'orange',
  permission_missing: 'rose',
  schema_changed: 'violet',
  data_inconsistent: 'sky',
};

const severityToneMap: Record<string, any> = {
  high: 'red',
  medium: 'amber',
  low: 'emerald',
};

export const ExceptionDetailPage: React.FC = () => {
  const { taskId, recordId } = useParams<{ taskId: string; recordId: string }>();
  const navigate = useNavigate();
  const { state, toggleExceptionStatus } = useApp();

  const [callChain, setCallChain] = useState<CallChainNode[]>([]);
  const [permissions, setPermissions] = useState<PermissionSnapshotType[]>([]);
  const [schema, setSchema] = useState<TableSchemaSnapshot | undefined>();
  const [opinions, setOpinions] = useState<TreatmentOpinion[]>([]);
  const [activeReviewAction, setActiveReviewAction] = useState<ReviewActionType | null>(null);

  const record: ExceptionRecord | undefined =
    state.exceptions.find((e) => e.id === recordId) ||
    (exceptionsMock as ExceptionRecord[]).find((e) => e.id === recordId) ||
    (tasksMock as any[]).find((t) => t.id === taskId)
      ? ({ id: recordId, taskId, eventId: 'EVT-ORD-7f3d9a2b1c', type: 'index_invalid', severity: 'high', status: 'pending', tableName: 'order_main', sourceService: 'order-service', eventTime: '2026-06-17T14:32:18+08:00', description: 'SQL走全表扫描，idx_order_created_at索引未被使用，扫描284万行' } as ExceptionRecord)
      : undefined;

  useEffect(() => {
    if (!recordId) return;
    api.getCallChain(recordId).then(setCallChain);
    api.getPermissionSnapshots(recordId).then(setPermissions);
    api.getSchemaSnapshot(recordId).then(setSchema);
    api.getTreatmentOpinions(recordId).then(setOpinions);
  }, [recordId]);

  const handleReviewActionClick = (type: ReviewActionType) => {
    setActiveReviewAction(type);
    if (type === 'rerun' || type === 'backfill') {
      toggleExceptionStatus(recordId!, 'reviewing');
    } else if (type === 'manual_confirm') {
      setTimeout(() => toggleExceptionStatus(recordId!, 'confirmed'), 8000);
    }
  };

  const handleAddOpinion = (content: string) => {
    const newOpinion: TreatmentOpinion = {
      id: 'OP-NEW-' + Date.now(),
      recordId: recordId!,
      author: '张明',
      authorRole: 'DBA · 数据平台',
      createTime: new Date().toISOString(),
      content,
      autoGenerated: false,
    };
    setOpinions((prev) => [...prev, newOpinion]);
  };

  if (!record) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-gray-400">
        <AlertTriangle className="w-12 h-12 mb-4" />
        <p className="text-lg font-medium">找不到异常记录</p>
        <p className="text-sm mt-1">ID: {recordId}</p>
        <Link to="/" className="mt-4 text-primary-600 hover:underline">
          返回任务列表
        </Link>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      <div className="bg-white border-b border-gray-200 px-6 py-3 no-print">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0 flex-1">
            <Button
              variant="ghost"
              size="sm"
              icon={<ArrowLeft className="w-4 h-4" />}
              onClick={() => navigate(-1)}
            >
              返回
            </Button>
            <div className="h-5 w-px bg-gray-200" />
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-mono text-xs font-bold text-primary-600">
                  {record.id}
                </span>
                <Tag tone={typeToneMap[record.type]}>
                  {getExceptionTypeLabel(record.type)}
                </Tag>
                <Tag tone={severityToneMap[record.severity]}>
                  {getSeverityLabel(record.severity)}
                </Tag>
                <div className="flex items-center gap-1.5">
                  <StatusDot color={getStatusDotColor(record.status)} />
                  <span
                    className={[
                      'text-xs font-medium inline-flex items-center px-2 py-0.5 border',
                      getRecordStatusColor(record.status),
                    ].join(' ')}
                  >
                    {getRecordStatusLabel(record.status)}
                  </span>
                </div>
                {record.assignee && (
                  <span className="inline-flex items-center gap-1 text-xs text-gray-600 bg-gray-50 border border-gray-200 px-2 py-0.5">
                    <User className="w-3 h-3" />
                    {record.assignee}
                  </span>
                )}
              </div>
              <h1 className="mt-1 text-base font-bold text-gray-900 leading-tight truncate">
                {record.description}
              </h1>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-shrink-0">
            <Button variant="secondary" size="sm" icon={<Copy className="w-4 h-4" />}>
              复制链接
            </Button>
            <Button variant="secondary" size="sm" icon={<Share2 className="w-4 h-4" />}>
              分享
            </Button>
            <Button variant="primary" size="sm" icon={<ExternalLink className="w-4 h-4" />}>
              跳转原系统
            </Button>
          </div>
        </div>

        <div className="mt-2.5 pt-2.5 border-t border-gray-100 grid grid-cols-6 gap-4 text-xs">
          <InfoCell label="所属任务" value={taskId || '—'} mono />
          <InfoCell label="事件ID" value={shortId(record.eventId, 14)} mono />
          <InfoCell label="所属表" value={record.tableName} mono />
          <InfoCell label="来源服务" value={record.sourceService} mono />
          <InfoCell label="事件时间" value={formatDateTime(record.eventTime)} />
          <InfoCell label="链路节点" value={`${callChain.length} 个`} />
        </div>
      </div>

      <div className="flex-1 overflow-y-auto bg-gray-50">
        <div className="max-w-[1600px] mx-auto p-5 space-y-5">
          <div className="grid grid-cols-2 gap-5">
            <div className="space-y-5">
              <SourceTracePanel
                nodes={callChain}
                eventId={record.eventId}
                eventTime={record.eventTime}
              />
              <SchemaSnapshotView schema={schema} />
            </div>
            <div className="space-y-5">
              {permissions.length > 0 && (
                <PermissionSnapshotView
                  snapshots={permissions}
                  showSideBySideToggle
                />
              )}
              <TreatmentOpinionView opinions={opinions} onAdd={handleAddOpinion} />
            </div>
          </div>
          <ReviewActions
            activeAction={activeReviewAction}
            onActionClick={handleReviewActionClick}
          />
        </div>
      </div>
    </div>
  );
};

const InfoCell: React.FC<{ label: string; value: string; mono?: boolean }> = ({
  label,
  value,
  mono,
}) => (
  <div>
    <div className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold mb-0.5">
      {label}
    </div>
    <div className={mono ? 'font-mono text-gray-800 font-medium' : 'text-gray-800 font-medium'}>
      {value}
    </div>
  </div>
);
