import type { Record, RecordHistory, CrossSectionData } from "./types";
import { v4 as uuidv4 } from "uuid";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400 * 1000).toISOString();

function makeCrossSection(overrides?: Partial<CrossSectionData>): CrossSectionData {
  return {
    points: [
      { x: 0, y: 0, z: 0 },
      { x: 2.5, y: -1.8, z: 0 },
      { x: 5, y: -3.2, z: 0.5 },
      { x: 7.5, y: -2.4, z: 1.2 },
      { x: 10, y: -0.6, z: 0 },
    ],
    parameters: { depth: 3.2, width: 10, height: 2.5 },
    annotations: [
      { position: { x: 2.5, y: -1.8, z: 0 }, text: "最低点" },
      { position: { x: 7.5, y: -2.4, z: 1.2 }, text: "拐点" },
    ],
    isComplete: true,
    ...overrides,
  };
}

export const MOCK_RECORDS: Record[] = [
  {
    id: "rec-001",
    recordNumber: "RS-2026-0607-001",
    timeParameter: daysAgo(0).slice(0, 19) + "Z",
    riskNote: "高风险：角度 68° 超过安全阈值 60°，同时时间参数与实际不一致，建议立即复核。",
    status: "anomaly",
    anomalyType: "TIME_MISMATCH",
    anomalyDescription:
      "记录的时间参数为 2026-06-07 14:32:00，但风险备注中提到的时间点为 14:27:00，两者相差 5 分钟。",
    anomalySuggestion: "修正时间参数或更新风险备注。",
    ropeAngle: 68,
    ropeLength: 45.2,
    ropeTension: 2890,
    anchorPointA: { x: 0, y: 10, z: 0 },
    anchorPointB: { x: 30, y: 2, z: 5 },
    crossSectionData: makeCrossSection(),
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
    operator: "李讲解员",
  },
  {
    id: "rec-002",
    recordNumber: "RS-2026-0607-002",
    timeParameter: hoursAgo(6).slice(0, 19) + "Z",
    riskNote: "",
    status: "anomaly",
    anomalyType: "RISK_NOTE_MISSING",
    anomalyDescription: "风险备注字段为空，仅填写了基础参数。",
    anomalySuggestion: "补充风险备注，至少包含角度值、张力读数和现场判断。",
    ropeAngle: 42,
    ropeLength: 38.6,
    ropeTension: 1560,
    anchorPointA: { x: 0, y: 8, z: 2 },
    anchorPointB: { x: 25, y: 4, z: 1 },
    crossSectionData: makeCrossSection({ isComplete: false }),
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
    operator: "王讲解员",
  },
  {
    id: "rec-003",
    recordNumber: "RS-2026-0607-003",
    timeParameter: hoursAgo(9).slice(0, 19) + "Z",
    riskNote: "角度 52°，现场存在透明保护罩遮挡传感器，读数已人工复核。",
    status: "anomaly",
    anomalyType: "TRANSPARENT_OCCLUSION",
    anomalyDescription:
      "系统检测到角度采样时存在透明介质遮挡，自动校正偏差约 8°，当前显示值可能不准确。",
    anomalySuggestion:
      "调整遮挡系数到 0.5 左右重新计算，或移除遮挡物后重新测量。",
    ropeAngle: 52,
    ropeLength: 52.8,
    ropeTension: 3120,
    anchorPointA: { x: 0, y: 12, z: 0 },
    anchorPointB: { x: 35, y: 5, z: 3 },
    crossSectionData: makeCrossSection(),
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(4),
    operator: "张讲解员",
  },
  {
    id: "rec-004",
    recordNumber: "RS-2026-0606-004",
    timeParameter: daysAgo(1).slice(0, 19) + "Z",
    riskNote: "正常：角度 38°，张力 1850kgf，符合安全规范。",
    status: "normal",
    ropeAngle: 38,
    ropeLength: 40.5,
    ropeTension: 1850,
    anchorPointA: { x: 0, y: 9, z: 1 },
    anchorPointB: { x: 28, y: 6, z: 2 },
    crossSectionData: makeCrossSection(),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    operator: "赵讲解员",
  },
  {
    id: "rec-005",
    recordNumber: "RS-2026-0606-005",
    timeParameter: daysAgo(1).slice(0, 19) + "Z",
    riskNote: "角度 195° 超出范围，怀疑传感器异常，需要重新测量。",
    status: "anomaly",
    anomalyType: "PARAM_OUT_OF_RANGE",
    anomalyDescription:
      "绳索角度 195° 超过合理范围 0~180°，极大概率是传感器翻转或录入错误。",
    anomalySuggestion: "修正角度参数至合理范围。",
    ropeAngle: 195,
    ropeLength: 48.0,
    ropeTension: 2400,
    anchorPointA: { x: 0, y: 10, z: 0 },
    anchorPointB: { x: 32, y: 3, z: 0 },
    crossSectionData: makeCrossSection(),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(20),
    operator: "李讲解员",
  },
  {
    id: "rec-006",
    recordNumber: "RS-2026-0606-006",
    timeParameter: daysAgo(2).slice(0, 19) + "Z",
    riskNote: "已修正：原时间参数错误，现更正为实际测量时间 10:15。",
    status: "corrected",
    ropeAngle: 45,
    ropeLength: 42.3,
    ropeTension: 2100,
    anchorPointA: { x: 0, y: 11, z: 0 },
    anchorPointB: { x: 29, y: 5, z: 2 },
    crossSectionData: makeCrossSection(),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    operator: "王讲解员",
  },
  {
    id: "rec-007",
    recordNumber: "RS-2026-0605-007",
    timeParameter: daysAgo(3).slice(0, 19) + "Z",
    riskNote: "待处理：数据格式存在异常，需要讲解员确认。",
    status: "pending",
    anomalyType: "DATA_FORMAT_ERROR",
    anomalyDescription: "导入时时间字段格式不规范，疑似使用了中文日期。",
    anomalySuggestion: "修正为 ISO-8601 格式 YYYY-MM-DDTHH:mm:ssZ。",
    ropeAngle: 50,
    ropeLength: 50.0,
    ropeTension: 2680,
    anchorPointA: { x: 0, y: 10, z: 1 },
    anchorPointB: { x: 33, y: 4, z: 1 },
    crossSectionData: makeCrossSection({ isComplete: false }),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    operator: "张讲解员",
  },
  {
    id: "rec-008",
    recordNumber: "RS-2026-0605-008",
    timeParameter: daysAgo(4).slice(0, 19) + "Z",
    riskNote: "正常：角度 40°，张力 1720kgf，现场条件良好。",
    status: "normal",
    ropeAngle: 40,
    ropeLength: 39.8,
    ropeTension: 1720,
    anchorPointA: { x: 0, y: 9, z: 2 },
    anchorPointB: { x: 27, y: 6, z: 2 },
    crossSectionData: makeCrossSection(),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    operator: "赵讲解员",
  },
];

export const MOCK_HISTORY: { [key: string]: RecordHistory[] } = {
  "rec-001": [
    {
      id: uuidv4(),
      recordId: "rec-001",
      version: 1,
      changes: [
        { field: "ropeAngle", fieldLabel: "绳索角度", oldValue: 65, newValue: 68 },
        { field: "ropeTension", fieldLabel: "绳索张力", oldValue: 2780, newValue: 2890 },
      ],
      operator: "李讲解员",
      operatedAt: hoursAgo(2),
      comment: "初版录入",
    },
    {
      id: uuidv4(),
      recordId: "rec-001",
      version: 2,
      changes: [
        {
          field: "timeParameter",
          fieldLabel: "时间参数",
          oldValue: "2026-06-07T14:27:00Z",
          newValue: "2026-06-07T14:32:00Z",
        },
      ],
      operator: "李讲解员",
      operatedAt: hoursAgo(1),
      comment: "时间参数录入错误，已调整（但与备注仍不一致，待复核）",
    },
  ],
  "rec-003": [
    {
      id: uuidv4(),
      recordId: "rec-003",
      version: 1,
      changes: [
        { field: "ropeAngle", fieldLabel: "绳索角度", oldValue: 60, newValue: 52 },
      ],
      operator: "张讲解员",
      operatedAt: hoursAgo(9),
      comment: "初版录入",
    },
    {
      id: uuidv4(),
      recordId: "rec-003",
      version: 2,
      changes: [
        {
          field: "riskNote",
          fieldLabel: "风险备注",
          oldValue: "角度读数异常",
          newValue: "角度 52°，现场存在透明保护罩遮挡传感器，读数已人工复核。",
        },
      ],
      operator: "张讲解员",
      operatedAt: hoursAgo(4),
      comment: "补充风险备注，说明遮挡情况",
    },
  ],
};

export function createNewRecord(): Record {
  const id = "rec-" + Math.random().toString(36).slice(2, 8);
  return {
    id,
    recordNumber: `RS-2026-${String(Math.floor(Math.random() * 9000) + 1000)}`,
    timeParameter: new Date().toISOString(),
    riskNote: "",
    status: "pending",
    ropeAngle: 45,
    ropeLength: 40,
    ropeTension: 2000,
    anchorPointA: { x: 0, y: 10, z: 0 },
    anchorPointB: { x: 30, y: 5, z: 2 },
    crossSectionData: makeCrossSection(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operator: "当前讲解员",
  };
}
